-- generated k2 regression data; not imported; verifier not yet written
-- Generated by scripts/kl2003_f2_k2_regression_generator_skeleton_v1.py
-- Schema: KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2
-- Mode: k2_regression
-- Mathematical content: baseline_reemission_only
-- Guardrails: no k=3 generation, no LP solving, no theorem claim.

namespace KL2003F2K2RegressionGenerated

def schemaVersion : String := "KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2"
def generatorMode : String := "k2_regression"
def mathematicalContent : String := "baseline_reemission_only"

def k : Nat := 2
def trackedClassCount : Nat := 3
def preReductionClassCount : Nat := 9

def sourceFaithfulContract : String := "V3"
def v2Status : String := "ABSTRACT_ONLY_NOT_SOURCE_FAITHFUL"
def m1v3SecondArm : String := "phi25"

def rowIds : List String := ["row22", "row25", "row28", "M1V3"]
def constantIds : List String := ["lambda", "gammaK2", "DeltaV2", "c22", "c25", "c28", "L2NT_D1_slack", "L2NT_D2_slack", "L2NT_D3_slack"]
def constantValues : List String := ["27/20", "logb 2 (27/20)", "(20/27)^14/2", "73/40", "1001/1000", "69/40", "29/9720", "271/729000", "2077/145800"]

-- The generated data above is a regression artifact only.  It contains no
-- theorem and is not imported by the trusted verifier yet.

end KL2003F2K2RegressionGenerated
