-- generated full k2 regression data; not imported; verifier not yet written
-- Generated by scripts/kl2003_f2_k2_full_generator_regression_v1.py
-- Schema: KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2_1
-- This file contains data declarations only and no mathematical theorem.

namespace KL2003F2K2FullRegressionGenerated

def schemaVersion : String := "KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2_1"
def generatorMode : String := "k2_full_regression"
def proofStatus : String := "generated_data_candidate_only"
def k : Nat := 2
def trackedClassCount : Nat := 3
def preReductionClassCount : Nat := 9
def rowIds : List String := ["row22", "row25", "row28"]
def auxiliaryBlockIds : List String := ["M1V3", "M2V3"]
def m1v3SecondArm : String := "phi25"
def constantIds : List String := ["lambda", "gammaK2", "DeltaV2", "c22", "c25", "c28", "L2NT_D1_slack", "L2NT_D2_slack", "L2NT_D3_slack"]
def constantValues : List String := ["27/20", "logb 2 (27/20)", "(20/27)^14/2", "73/40", "1001/1000", "69/40", "29/9720", "271/729000", "2077/145800"]
def recomputedSlackValues : List String := ["29/9720", "271/729000", "2077/145800"]
def deletedFigureNodeIds : List String := ["N04", "N05"]

-- Candidate data only.  The existing manual Lean theorems remain the source
-- of truth until a generated-data verifier rechecks this artifact.

end KL2003F2K2FullRegressionGenerated
