-- generated k2 row25 data; not imported; verifier not yet written
-- Generated by scripts/kl2003_f2_k2_row25_microgenerator_v1.py
-- Schema: KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2
-- Mode: rule_derived_row25
-- Scope: k2_row25_only
-- This file contains data declarations only and no mathematical theorem.

namespace KL2003F2K2Row25Generated

def schemaVersion : String := "KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2"
def generationMode : String := "rule_derived_row25"
def scope : String := "k2_row25_only"
def proofStatus : String := "data_candidate_only"

def k : Nat := 2
def trackedClassCount : Nat := 3
def preReductionClassCount : Nat := 9

def rowId : String := "row25"
def sourceResidueMod9 : Nat := 5
def retardedChildFormula : String := "4*a"
def retardedChildResidueMod9 : Nat := 2
def shift : String := "-2"
def windowPolicy : String := "exact_retarded_window"
def advancedContributionInEL : Bool := false

def constantIds : List String := ["lambda", "DeltaV2", "c22", "c25", "L2NT_D2_slack"]
def constantValues : List String := ["27/20", "(20/27)^14/2", "73/40", "1001/1000", "271/729000"]

-- Candidate data only.  A future verifier must prove residue, route, window,
-- and slack obligations before any theorem may consume this generated data.

end KL2003F2K2Row25Generated
