-- generated k2 row28 data; not imported; verifier not yet written
-- Generated by scripts/kl2003_f2_k2_row28_microgenerator_v1.py
-- Schema: KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2_1
-- Mode: rule_derived_row28
-- This file contains deterministic data declarations and no theorem.

namespace KL2003F2K2Row28Generated

def schemaVersion : String := "KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2_1"
def generationMode : String := "rule_derived_row28"
def proofStatus : String := "data_candidate_only"

def k : Nat := 2
def trackedClassCount : Nat := 3
def preReductionClassCount : Nat := 9
def rowId : String := "row28"
def sourceResidueMod9 : Nat := 8
def generatedTreeNodeCount : Nat := 16
def generatedTreeEdgeCount : Nat := 15
def deletedFigureNodeIds : List String := ["N04", "N05"]
def nestedBlockIds : List String := ["M2V3", "M1V3", "row28_outer_block"]
def m1v3SecondArm : String := "phi25"
def cSplitResidues : List Nat := [5, 2, 8]
def cPrimeSplitResidues : List Nat := [2, 5, 8]
def constantIds : List String := ["lambda", "DeltaV2", "c22", "c25", "c28", "L2NT_D3_slack"]
def constantValues : List String := ["27/20", "(20/27)^14/2", "73/40", "1001/1000", "69/40", "2077/145800"]

-- Candidate data only.  A future verifier must prove the route, window,
-- deletion, disjointness, nested-block, and positive-slack obligations.

end KL2003F2K2Row28Generated
