import Mathlib.Data.Rat.Defs

/- This file is generated by kl2003_f2_k3_generator_real_v1.py.
It is data, not a theorem.  The verifier must recheck every property. -/

namespace CollatzClassical.KL2003.GeneratedK3

structure TreeNodeData where
  rootMode : Nat
  nodeIndex : Nat
  isRoot : Bool
  parentIndex : Nat
  isMin : Bool
  mode : Nat
  alphaCoeff : Int
  const : Int
  status : Nat
  expansionDepth : Nat
  deletionAncestorIndex : Nat
  childIndices : List Nat
deriving Repr, DecidableEq

def lambda : Rat := (152759 / 100000 : Rat)
def aCoeff : Rat := (10000000000 / 23335312081 : Rat)
def bLower : Rat := (104843 / 125000 : Rat)
def dLower : Rat := (16015711837 / 12500000000 : Rat)
def alphaLower : Rat := (569 / 359 : Rat)

def c3_2 : Rat := (13629 / 5023 : Rat)
def c3_5 : Rat := (10113 / 8971 : Rat)
def c3_8 : Rat := (17497 / 9917 : Rat)
def c3_11 : Rat := (19632 / 8413 : Rat)
def c3_14 : Rat := (7723 / 6642 : Rat)
def c3_17 : Rat := (31599 / 9059 : Rat)
def c3_20 : Rat := (17183 / 6532 : Rat)
def c3_23 : Rat := (1 / 1 : Rat)
def c3_26 : Rat := (11461 / 4262 : Rat)

def c2_2 : Rat := (19632 / 8413 : Rat)
def c2_5 : Rat := (1 / 1 : Rat)
def c2_8 : Rat := (17497 / 9917 : Rat)

def slack_m2 : Rat := (304795542269005271 / 3251098755196268350140625 : Rat)
def slack_m5 : Rat := (44414275151 / 341853991280237083 : Rat)
def slack_m8 : Rat := (2562311206697981843379 / 25950444209477274587500000000 : Rat)
def slack_m11 : Rat := (19876917800818861 / 222307837961098340875000 : Rat)
def slack_m14 : Rat := (75842549051 / 778530556495376046 : Rat)
def slack_m17 : Rat := (590499070911102882417941 / 4614277061680047437786718750000 : Rat)
def slack_m20 : Rat := (163521331496785684269623 / 100663858727875137458875000 : Rat)
def slack_m23 : Rat := (19462547 / 196319980537453 : Rat)
def slack_m26 : Rat := (450047250673244841279 / 6164351422405091087500000000 : Rat)

def principal : List (Nat × Rat) := [
    (2, (13629 / 5023 : Rat)),
    (5, (10113 / 8971 : Rat)),
    (8, (17497 / 9917 : Rat)),
    (11, (19632 / 8413 : Rat)),
    (14, (7723 / 6642 : Rat)),
    (17, (31599 / 9059 : Rat)),
    (20, (17183 / 6532 : Rat)),
    (23, (1 / 1 : Rat)),
    (26, (11461 / 4262 : Rat))
  ]

def auxiliary : List (Nat × Rat) := [
    (2, (19632 / 8413 : Rat)),
    (5, (1 / 1 : Rat)),
    (8, (17497 / 9917 : Rat))
  ]

def rowSlacks : List (Nat × Rat) := [
    (2, (304795542269005271 / 3251098755196268350140625 : Rat)),
    (5, (44414275151 / 341853991280237083 : Rat)),
    (8, (2562311206697981843379 / 25950444209477274587500000000 : Rat)),
    (11, (19876917800818861 / 222307837961098340875000 : Rat)),
    (14, (75842549051 / 778530556495376046 : Rat)),
    (17, (590499070911102882417941 / 4614277061680047437786718750000 : Rat)),
    (20, (163521331496785684269623 / 100663858727875137458875000 : Rat)),
    (23, (19462547 / 196319980537453 : Rat)),
    (26, (450047250673244841279 / 6164351422405091087500000000 : Rat))
  ]

def treeMetrics : List (Nat × Nat × Nat × Nat) := [
    (8, 4, 0, 2),
    (17, 28, 3, 5),
    (26, 84, 7, 10)
  ]

def treeNodes8 : Array TreeNodeData := #[
    { rootMode := 8, nodeIndex := 0, isRoot := true, parentIndex := 0, isMin := false, mode := 8, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 0, deletionAncestorIndex := 0, childIndices := [1, 2] },
    { rootMode := 8, nodeIndex := 1, isRoot := false, parentIndex := 0, isMin := false, mode := 5, alphaCoeff := 0, const := -2, status := 1, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 8, nodeIndex := 2, isRoot := false, parentIndex := 0, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [3, 4, 5] },
    { rootMode := 8, nodeIndex := 3, isRoot := false, parentIndex := 2, isMin := false, mode := 5, alphaCoeff := 1, const := -1, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [6] },
    { rootMode := 8, nodeIndex := 4, isRoot := false, parentIndex := 2, isMin := false, mode := 14, alphaCoeff := 1, const := -1, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [7] },
    { rootMode := 8, nodeIndex := 5, isRoot := false, parentIndex := 2, isMin := false, mode := 23, alphaCoeff := 1, const := -1, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [8] },
    { rootMode := 8, nodeIndex := 6, isRoot := false, parentIndex := 3, isMin := false, mode := 20, alphaCoeff := 1, const := -3, status := 1, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 8, nodeIndex := 7, isRoot := false, parentIndex := 4, isMin := false, mode := 2, alphaCoeff := 1, const := -3, status := 1, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 8, nodeIndex := 8, isRoot := false, parentIndex := 5, isMin := false, mode := 11, alphaCoeff := 1, const := -3, status := 1, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] }
  ]

def treeNodes17 : Array TreeNodeData := #[
    { rootMode := 17, nodeIndex := 0, isRoot := true, parentIndex := 0, isMin := false, mode := 17, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 0, deletionAncestorIndex := 0, childIndices := [1, 2] },
    { rootMode := 17, nodeIndex := 1, isRoot := false, parentIndex := 0, isMin := false, mode := 14, alphaCoeff := 0, const := -2, status := 1, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 2, isRoot := false, parentIndex := 0, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [3, 4, 5] },
    { rootMode := 17, nodeIndex := 3, isRoot := false, parentIndex := 2, isMin := false, mode := 2, alphaCoeff := 1, const := -1, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [6, 7] },
    { rootMode := 17, nodeIndex := 4, isRoot := false, parentIndex := 2, isMin := false, mode := 11, alphaCoeff := 1, const := -1, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [11, 12] },
    { rootMode := 17, nodeIndex := 5, isRoot := false, parentIndex := 2, isMin := false, mode := 20, alphaCoeff := 1, const := -1, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [16, 17] },
    { rootMode := 17, nodeIndex := 6, isRoot := false, parentIndex := 3, isMin := false, mode := 8, alphaCoeff := 1, const := -3, status := 1, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 7, isRoot := false, parentIndex := 3, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [8, 9, 10] },
    { rootMode := 17, nodeIndex := 8, isRoot := false, parentIndex := 7, isMin := false, mode := 2, alphaCoeff := 2, const := -3, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [21, 22] },
    { rootMode := 17, nodeIndex := 9, isRoot := false, parentIndex := 7, isMin := false, mode := 11, alphaCoeff := 2, const := -3, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [26, 27] },
    { rootMode := 17, nodeIndex := 10, isRoot := false, parentIndex := 7, isMin := false, mode := 20, alphaCoeff := 2, const := -3, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [31, 32] },
    { rootMode := 17, nodeIndex := 11, isRoot := false, parentIndex := 4, isMin := false, mode := 17, alphaCoeff := 1, const := -3, status := 1, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 12, isRoot := false, parentIndex := 4, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [13, 14, 15] },
    { rootMode := 17, nodeIndex := 13, isRoot := false, parentIndex := 12, isMin := false, mode := 5, alphaCoeff := 2, const := -3, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [36] },
    { rootMode := 17, nodeIndex := 14, isRoot := false, parentIndex := 12, isMin := false, mode := 14, alphaCoeff := 2, const := -3, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [37] },
    { rootMode := 17, nodeIndex := 15, isRoot := false, parentIndex := 12, isMin := false, mode := 23, alphaCoeff := 2, const := -3, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [38] },
    { rootMode := 17, nodeIndex := 16, isRoot := false, parentIndex := 5, isMin := false, mode := 26, alphaCoeff := 1, const := -3, status := 1, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 17, isRoot := false, parentIndex := 5, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [18, 19, 20] },
    { rootMode := 17, nodeIndex := 18, isRoot := false, parentIndex := 17, isMin := false, mode := 8, alphaCoeff := 2, const := -3, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [39, 40] },
    { rootMode := 17, nodeIndex := 19, isRoot := false, parentIndex := 17, isMin := false, mode := 17, alphaCoeff := 2, const := -3, status := 2, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 20, isRoot := false, parentIndex := 17, isMin := false, mode := 26, alphaCoeff := 2, const := -3, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [44, 45] },
    { rootMode := 17, nodeIndex := 21, isRoot := false, parentIndex := 8, isMin := false, mode := 8, alphaCoeff := 2, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 22, isRoot := false, parentIndex := 8, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [23, 24, 25] },
    { rootMode := 17, nodeIndex := 23, isRoot := false, parentIndex := 22, isMin := false, mode := 2, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 24, isRoot := false, parentIndex := 22, isMin := false, mode := 11, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 25, isRoot := false, parentIndex := 22, isMin := false, mode := 20, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 26, isRoot := false, parentIndex := 9, isMin := false, mode := 17, alphaCoeff := 2, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 27, isRoot := false, parentIndex := 9, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [28, 29, 30] },
    { rootMode := 17, nodeIndex := 28, isRoot := false, parentIndex := 27, isMin := false, mode := 5, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 29, isRoot := false, parentIndex := 27, isMin := false, mode := 14, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 30, isRoot := false, parentIndex := 27, isMin := false, mode := 23, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 31, isRoot := false, parentIndex := 10, isMin := false, mode := 26, alphaCoeff := 2, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 32, isRoot := false, parentIndex := 10, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [33, 34, 35] },
    { rootMode := 17, nodeIndex := 33, isRoot := false, parentIndex := 32, isMin := false, mode := 8, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 34, isRoot := false, parentIndex := 32, isMin := false, mode := 17, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 35, isRoot := false, parentIndex := 32, isMin := false, mode := 26, alphaCoeff := 3, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 36, isRoot := false, parentIndex := 13, isMin := false, mode := 20, alphaCoeff := 2, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 37, isRoot := false, parentIndex := 14, isMin := false, mode := 2, alphaCoeff := 2, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 38, isRoot := false, parentIndex := 15, isMin := false, mode := 11, alphaCoeff := 2, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 39, isRoot := false, parentIndex := 18, isMin := false, mode := 5, alphaCoeff := 2, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 40, isRoot := false, parentIndex := 18, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [41, 42, 43] },
    { rootMode := 17, nodeIndex := 41, isRoot := false, parentIndex := 40, isMin := false, mode := 5, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [49] },
    { rootMode := 17, nodeIndex := 42, isRoot := false, parentIndex := 40, isMin := false, mode := 14, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [50] },
    { rootMode := 17, nodeIndex := 43, isRoot := false, parentIndex := 40, isMin := false, mode := 23, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [51] },
    { rootMode := 17, nodeIndex := 44, isRoot := false, parentIndex := 20, isMin := false, mode := 23, alphaCoeff := 2, const := -5, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 45, isRoot := false, parentIndex := 20, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [46, 47, 48] },
    { rootMode := 17, nodeIndex := 46, isRoot := false, parentIndex := 45, isMin := false, mode := 8, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [52, 53] },
    { rootMode := 17, nodeIndex := 47, isRoot := false, parentIndex := 45, isMin := false, mode := 17, alphaCoeff := 3, const := -4, status := 2, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 48, isRoot := false, parentIndex := 45, isMin := false, mode := 26, alphaCoeff := 3, const := -4, status := 2, expansionDepth := 3, deletionAncestorIndex := 20, childIndices := [] },
    { rootMode := 17, nodeIndex := 49, isRoot := false, parentIndex := 41, isMin := false, mode := 20, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 50, isRoot := false, parentIndex := 42, isMin := false, mode := 2, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 51, isRoot := false, parentIndex := 43, isMin := false, mode := 11, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 52, isRoot := false, parentIndex := 46, isMin := false, mode := 5, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 53, isRoot := false, parentIndex := 46, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [54, 55, 56] },
    { rootMode := 17, nodeIndex := 54, isRoot := false, parentIndex := 53, isMin := false, mode := 5, alphaCoeff := 4, const := -5, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [57] },
    { rootMode := 17, nodeIndex := 55, isRoot := false, parentIndex := 53, isMin := false, mode := 14, alphaCoeff := 4, const := -5, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [58] },
    { rootMode := 17, nodeIndex := 56, isRoot := false, parentIndex := 53, isMin := false, mode := 23, alphaCoeff := 4, const := -5, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [59] },
    { rootMode := 17, nodeIndex := 57, isRoot := false, parentIndex := 54, isMin := false, mode := 20, alphaCoeff := 4, const := -7, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 58, isRoot := false, parentIndex := 55, isMin := false, mode := 2, alphaCoeff := 4, const := -7, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 17, nodeIndex := 59, isRoot := false, parentIndex := 56, isMin := false, mode := 11, alphaCoeff := 4, const := -7, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] }
  ]

def treeNodes26 : Array TreeNodeData := #[
    { rootMode := 26, nodeIndex := 0, isRoot := true, parentIndex := 0, isMin := false, mode := 26, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 0, deletionAncestorIndex := 0, childIndices := [1, 2] },
    { rootMode := 26, nodeIndex := 1, isRoot := false, parentIndex := 0, isMin := false, mode := 23, alphaCoeff := 0, const := -2, status := 1, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 2, isRoot := false, parentIndex := 0, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [3, 4, 5] },
    { rootMode := 26, nodeIndex := 3, isRoot := false, parentIndex := 2, isMin := false, mode := 8, alphaCoeff := 1, const := -1, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [6, 7] },
    { rootMode := 26, nodeIndex := 4, isRoot := false, parentIndex := 2, isMin := false, mode := 17, alphaCoeff := 1, const := -1, status := 0, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [11, 12] },
    { rootMode := 26, nodeIndex := 5, isRoot := false, parentIndex := 2, isMin := false, mode := 26, alphaCoeff := 1, const := -1, status := 2, expansionDepth := 1, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 6, isRoot := false, parentIndex := 3, isMin := false, mode := 5, alphaCoeff := 1, const := -3, status := 1, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 7, isRoot := false, parentIndex := 3, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [8, 9, 10] },
    { rootMode := 26, nodeIndex := 8, isRoot := false, parentIndex := 7, isMin := false, mode := 5, alphaCoeff := 2, const := -2, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [16] },
    { rootMode := 26, nodeIndex := 9, isRoot := false, parentIndex := 7, isMin := false, mode := 14, alphaCoeff := 2, const := -2, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [17] },
    { rootMode := 26, nodeIndex := 10, isRoot := false, parentIndex := 7, isMin := false, mode := 23, alphaCoeff := 2, const := -2, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [18] },
    { rootMode := 26, nodeIndex := 11, isRoot := false, parentIndex := 4, isMin := false, mode := 14, alphaCoeff := 1, const := -3, status := 1, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 12, isRoot := false, parentIndex := 4, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [13, 14, 15] },
    { rootMode := 26, nodeIndex := 13, isRoot := false, parentIndex := 12, isMin := false, mode := 2, alphaCoeff := 2, const := -2, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [19, 20] },
    { rootMode := 26, nodeIndex := 14, isRoot := false, parentIndex := 12, isMin := false, mode := 11, alphaCoeff := 2, const := -2, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [24, 25] },
    { rootMode := 26, nodeIndex := 15, isRoot := false, parentIndex := 12, isMin := false, mode := 20, alphaCoeff := 2, const := -2, status := 0, expansionDepth := 2, deletionAncestorIndex := 0, childIndices := [29, 30] },
    { rootMode := 26, nodeIndex := 16, isRoot := false, parentIndex := 8, isMin := false, mode := 20, alphaCoeff := 2, const := -4, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 17, isRoot := false, parentIndex := 9, isMin := false, mode := 2, alphaCoeff := 2, const := -4, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 18, isRoot := false, parentIndex := 10, isMin := false, mode := 11, alphaCoeff := 2, const := -4, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 19, isRoot := false, parentIndex := 13, isMin := false, mode := 8, alphaCoeff := 2, const := -4, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 20, isRoot := false, parentIndex := 13, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [21, 22, 23] },
    { rootMode := 26, nodeIndex := 21, isRoot := false, parentIndex := 20, isMin := false, mode := 2, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [34, 35] },
    { rootMode := 26, nodeIndex := 22, isRoot := false, parentIndex := 20, isMin := false, mode := 11, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [39, 40] },
    { rootMode := 26, nodeIndex := 23, isRoot := false, parentIndex := 20, isMin := false, mode := 20, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [44, 45] },
    { rootMode := 26, nodeIndex := 24, isRoot := false, parentIndex := 14, isMin := false, mode := 17, alphaCoeff := 2, const := -4, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 25, isRoot := false, parentIndex := 14, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [26, 27, 28] },
    { rootMode := 26, nodeIndex := 26, isRoot := false, parentIndex := 25, isMin := false, mode := 5, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [49] },
    { rootMode := 26, nodeIndex := 27, isRoot := false, parentIndex := 25, isMin := false, mode := 14, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [50] },
    { rootMode := 26, nodeIndex := 28, isRoot := false, parentIndex := 25, isMin := false, mode := 23, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [51] },
    { rootMode := 26, nodeIndex := 29, isRoot := false, parentIndex := 15, isMin := false, mode := 26, alphaCoeff := 2, const := -4, status := 1, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 30, isRoot := false, parentIndex := 15, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [31, 32, 33] },
    { rootMode := 26, nodeIndex := 31, isRoot := false, parentIndex := 30, isMin := false, mode := 8, alphaCoeff := 3, const := -4, status := 0, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [52, 53] },
    { rootMode := 26, nodeIndex := 32, isRoot := false, parentIndex := 30, isMin := false, mode := 17, alphaCoeff := 3, const := -4, status := 2, expansionDepth := 3, deletionAncestorIndex := 4, childIndices := [] },
    { rootMode := 26, nodeIndex := 33, isRoot := false, parentIndex := 30, isMin := false, mode := 26, alphaCoeff := 3, const := -4, status := 2, expansionDepth := 3, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 34, isRoot := false, parentIndex := 21, isMin := false, mode := 8, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 35, isRoot := false, parentIndex := 21, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [36, 37, 38] },
    { rootMode := 26, nodeIndex := 36, isRoot := false, parentIndex := 35, isMin := false, mode := 2, alphaCoeff := 4, const := -6, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [57, 58] },
    { rootMode := 26, nodeIndex := 37, isRoot := false, parentIndex := 35, isMin := false, mode := 11, alphaCoeff := 4, const := -6, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [62, 63] },
    { rootMode := 26, nodeIndex := 38, isRoot := false, parentIndex := 35, isMin := false, mode := 20, alphaCoeff := 4, const := -6, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [67, 68] },
    { rootMode := 26, nodeIndex := 39, isRoot := false, parentIndex := 22, isMin := false, mode := 17, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 40, isRoot := false, parentIndex := 22, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [41, 42, 43] },
    { rootMode := 26, nodeIndex := 41, isRoot := false, parentIndex := 40, isMin := false, mode := 5, alphaCoeff := 4, const := -6, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [72] },
    { rootMode := 26, nodeIndex := 42, isRoot := false, parentIndex := 40, isMin := false, mode := 14, alphaCoeff := 4, const := -6, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [73] },
    { rootMode := 26, nodeIndex := 43, isRoot := false, parentIndex := 40, isMin := false, mode := 23, alphaCoeff := 4, const := -6, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [74] },
    { rootMode := 26, nodeIndex := 44, isRoot := false, parentIndex := 23, isMin := false, mode := 26, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 45, isRoot := false, parentIndex := 23, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [46, 47, 48] },
    { rootMode := 26, nodeIndex := 46, isRoot := false, parentIndex := 45, isMin := false, mode := 8, alphaCoeff := 4, const := -6, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [75, 76] },
    { rootMode := 26, nodeIndex := 47, isRoot := false, parentIndex := 45, isMin := false, mode := 17, alphaCoeff := 4, const := -6, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [80, 81] },
    { rootMode := 26, nodeIndex := 48, isRoot := false, parentIndex := 45, isMin := false, mode := 26, alphaCoeff := 4, const := -6, status := 2, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 49, isRoot := false, parentIndex := 26, isMin := false, mode := 20, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 50, isRoot := false, parentIndex := 27, isMin := false, mode := 2, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 51, isRoot := false, parentIndex := 28, isMin := false, mode := 11, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 52, isRoot := false, parentIndex := 31, isMin := false, mode := 5, alphaCoeff := 3, const := -6, status := 1, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 53, isRoot := false, parentIndex := 31, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [54, 55, 56] },
    { rootMode := 26, nodeIndex := 54, isRoot := false, parentIndex := 53, isMin := false, mode := 5, alphaCoeff := 4, const := -5, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [85] },
    { rootMode := 26, nodeIndex := 55, isRoot := false, parentIndex := 53, isMin := false, mode := 14, alphaCoeff := 4, const := -5, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [86] },
    { rootMode := 26, nodeIndex := 56, isRoot := false, parentIndex := 53, isMin := false, mode := 23, alphaCoeff := 4, const := -5, status := 0, expansionDepth := 4, deletionAncestorIndex := 0, childIndices := [87] },
    { rootMode := 26, nodeIndex := 57, isRoot := false, parentIndex := 36, isMin := false, mode := 8, alphaCoeff := 4, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 58, isRoot := false, parentIndex := 36, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [59, 60, 61] },
    { rootMode := 26, nodeIndex := 59, isRoot := false, parentIndex := 58, isMin := false, mode := 2, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 60, isRoot := false, parentIndex := 58, isMin := false, mode := 11, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 61, isRoot := false, parentIndex := 58, isMin := false, mode := 20, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 62, isRoot := false, parentIndex := 37, isMin := false, mode := 17, alphaCoeff := 4, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 63, isRoot := false, parentIndex := 37, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [64, 65, 66] },
    { rootMode := 26, nodeIndex := 64, isRoot := false, parentIndex := 63, isMin := false, mode := 5, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 65, isRoot := false, parentIndex := 63, isMin := false, mode := 14, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 66, isRoot := false, parentIndex := 63, isMin := false, mode := 23, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 67, isRoot := false, parentIndex := 38, isMin := false, mode := 26, alphaCoeff := 4, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 68, isRoot := false, parentIndex := 38, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [69, 70, 71] },
    { rootMode := 26, nodeIndex := 69, isRoot := false, parentIndex := 68, isMin := false, mode := 8, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 70, isRoot := false, parentIndex := 68, isMin := false, mode := 17, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 71, isRoot := false, parentIndex := 68, isMin := false, mode := 26, alphaCoeff := 5, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 72, isRoot := false, parentIndex := 41, isMin := false, mode := 20, alphaCoeff := 4, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 73, isRoot := false, parentIndex := 42, isMin := false, mode := 2, alphaCoeff := 4, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 74, isRoot := false, parentIndex := 43, isMin := false, mode := 11, alphaCoeff := 4, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 75, isRoot := false, parentIndex := 46, isMin := false, mode := 5, alphaCoeff := 4, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 76, isRoot := false, parentIndex := 46, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [77, 78, 79] },
    { rootMode := 26, nodeIndex := 77, isRoot := false, parentIndex := 76, isMin := false, mode := 5, alphaCoeff := 5, const := -7, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [88] },
    { rootMode := 26, nodeIndex := 78, isRoot := false, parentIndex := 76, isMin := false, mode := 14, alphaCoeff := 5, const := -7, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [89] },
    { rootMode := 26, nodeIndex := 79, isRoot := false, parentIndex := 76, isMin := false, mode := 23, alphaCoeff := 5, const := -7, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [90] },
    { rootMode := 26, nodeIndex := 80, isRoot := false, parentIndex := 47, isMin := false, mode := 14, alphaCoeff := 4, const := -8, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 81, isRoot := false, parentIndex := 47, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [82, 83, 84] },
    { rootMode := 26, nodeIndex := 82, isRoot := false, parentIndex := 81, isMin := false, mode := 2, alphaCoeff := 5, const := -7, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [91, 92] },
    { rootMode := 26, nodeIndex := 83, isRoot := false, parentIndex := 81, isMin := false, mode := 11, alphaCoeff := 5, const := -7, status := 0, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [96, 97] },
    { rootMode := 26, nodeIndex := 84, isRoot := false, parentIndex := 81, isMin := false, mode := 20, alphaCoeff := 5, const := -7, status := 2, expansionDepth := 5, deletionAncestorIndex := 23, childIndices := [] },
    { rootMode := 26, nodeIndex := 85, isRoot := false, parentIndex := 54, isMin := false, mode := 20, alphaCoeff := 4, const := -7, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 86, isRoot := false, parentIndex := 55, isMin := false, mode := 2, alphaCoeff := 4, const := -7, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 87, isRoot := false, parentIndex := 56, isMin := false, mode := 11, alphaCoeff := 4, const := -7, status := 1, expansionDepth := 5, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 88, isRoot := false, parentIndex := 77, isMin := false, mode := 20, alphaCoeff := 5, const := -9, status := 1, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 89, isRoot := false, parentIndex := 78, isMin := false, mode := 2, alphaCoeff := 5, const := -9, status := 1, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 90, isRoot := false, parentIndex := 79, isMin := false, mode := 11, alphaCoeff := 5, const := -9, status := 1, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 91, isRoot := false, parentIndex := 82, isMin := false, mode := 8, alphaCoeff := 5, const := -9, status := 1, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 92, isRoot := false, parentIndex := 82, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [93, 94, 95] },
    { rootMode := 26, nodeIndex := 93, isRoot := false, parentIndex := 92, isMin := false, mode := 2, alphaCoeff := 6, const := -9, status := 0, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [101, 102] },
    { rootMode := 26, nodeIndex := 94, isRoot := false, parentIndex := 92, isMin := false, mode := 11, alphaCoeff := 6, const := -9, status := 0, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [106, 107] },
    { rootMode := 26, nodeIndex := 95, isRoot := false, parentIndex := 92, isMin := false, mode := 20, alphaCoeff := 6, const := -9, status := 0, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [111, 112] },
    { rootMode := 26, nodeIndex := 96, isRoot := false, parentIndex := 83, isMin := false, mode := 17, alphaCoeff := 5, const := -9, status := 1, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 97, isRoot := false, parentIndex := 83, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [98, 99, 100] },
    { rootMode := 26, nodeIndex := 98, isRoot := false, parentIndex := 97, isMin := false, mode := 5, alphaCoeff := 6, const := -9, status := 0, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [116] },
    { rootMode := 26, nodeIndex := 99, isRoot := false, parentIndex := 97, isMin := false, mode := 14, alphaCoeff := 6, const := -9, status := 0, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [117] },
    { rootMode := 26, nodeIndex := 100, isRoot := false, parentIndex := 97, isMin := false, mode := 23, alphaCoeff := 6, const := -9, status := 0, expansionDepth := 6, deletionAncestorIndex := 0, childIndices := [118] },
    { rootMode := 26, nodeIndex := 101, isRoot := false, parentIndex := 93, isMin := false, mode := 8, alphaCoeff := 6, const := -11, status := 1, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 102, isRoot := false, parentIndex := 93, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [103, 104, 105] },
    { rootMode := 26, nodeIndex := 103, isRoot := false, parentIndex := 102, isMin := false, mode := 2, alphaCoeff := 7, const := -11, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [119, 120] },
    { rootMode := 26, nodeIndex := 104, isRoot := false, parentIndex := 102, isMin := false, mode := 11, alphaCoeff := 7, const := -11, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [124, 125] },
    { rootMode := 26, nodeIndex := 105, isRoot := false, parentIndex := 102, isMin := false, mode := 20, alphaCoeff := 7, const := -11, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [129, 130] },
    { rootMode := 26, nodeIndex := 106, isRoot := false, parentIndex := 94, isMin := false, mode := 17, alphaCoeff := 6, const := -11, status := 1, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 107, isRoot := false, parentIndex := 94, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [108, 109, 110] },
    { rootMode := 26, nodeIndex := 108, isRoot := false, parentIndex := 107, isMin := false, mode := 5, alphaCoeff := 7, const := -11, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [134] },
    { rootMode := 26, nodeIndex := 109, isRoot := false, parentIndex := 107, isMin := false, mode := 14, alphaCoeff := 7, const := -11, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [135] },
    { rootMode := 26, nodeIndex := 110, isRoot := false, parentIndex := 107, isMin := false, mode := 23, alphaCoeff := 7, const := -11, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [136] },
    { rootMode := 26, nodeIndex := 111, isRoot := false, parentIndex := 95, isMin := false, mode := 26, alphaCoeff := 6, const := -11, status := 1, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 112, isRoot := false, parentIndex := 95, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [113, 114, 115] },
    { rootMode := 26, nodeIndex := 113, isRoot := false, parentIndex := 112, isMin := false, mode := 8, alphaCoeff := 7, const := -11, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [137, 138] },
    { rootMode := 26, nodeIndex := 114, isRoot := false, parentIndex := 112, isMin := false, mode := 17, alphaCoeff := 7, const := -11, status := 0, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [142, 143] },
    { rootMode := 26, nodeIndex := 115, isRoot := false, parentIndex := 112, isMin := false, mode := 26, alphaCoeff := 7, const := -11, status := 2, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 116, isRoot := false, parentIndex := 98, isMin := false, mode := 20, alphaCoeff := 6, const := -11, status := 1, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 117, isRoot := false, parentIndex := 99, isMin := false, mode := 2, alphaCoeff := 6, const := -11, status := 1, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 118, isRoot := false, parentIndex := 100, isMin := false, mode := 11, alphaCoeff := 6, const := -11, status := 1, expansionDepth := 7, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 119, isRoot := false, parentIndex := 103, isMin := false, mode := 8, alphaCoeff := 7, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 120, isRoot := false, parentIndex := 103, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [121, 122, 123] },
    { rootMode := 26, nodeIndex := 121, isRoot := false, parentIndex := 120, isMin := false, mode := 2, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 122, isRoot := false, parentIndex := 120, isMin := false, mode := 11, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 123, isRoot := false, parentIndex := 120, isMin := false, mode := 20, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 124, isRoot := false, parentIndex := 104, isMin := false, mode := 17, alphaCoeff := 7, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 125, isRoot := false, parentIndex := 104, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [126, 127, 128] },
    { rootMode := 26, nodeIndex := 126, isRoot := false, parentIndex := 125, isMin := false, mode := 5, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 127, isRoot := false, parentIndex := 125, isMin := false, mode := 14, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 128, isRoot := false, parentIndex := 125, isMin := false, mode := 23, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 129, isRoot := false, parentIndex := 105, isMin := false, mode := 26, alphaCoeff := 7, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 130, isRoot := false, parentIndex := 105, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [131, 132, 133] },
    { rootMode := 26, nodeIndex := 131, isRoot := false, parentIndex := 130, isMin := false, mode := 8, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 132, isRoot := false, parentIndex := 130, isMin := false, mode := 17, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 133, isRoot := false, parentIndex := 130, isMin := false, mode := 26, alphaCoeff := 8, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 134, isRoot := false, parentIndex := 108, isMin := false, mode := 20, alphaCoeff := 7, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 135, isRoot := false, parentIndex := 109, isMin := false, mode := 2, alphaCoeff := 7, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 136, isRoot := false, parentIndex := 110, isMin := false, mode := 11, alphaCoeff := 7, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 137, isRoot := false, parentIndex := 113, isMin := false, mode := 5, alphaCoeff := 7, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 138, isRoot := false, parentIndex := 113, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [139, 140, 141] },
    { rootMode := 26, nodeIndex := 139, isRoot := false, parentIndex := 138, isMin := false, mode := 5, alphaCoeff := 8, const := -12, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [147] },
    { rootMode := 26, nodeIndex := 140, isRoot := false, parentIndex := 138, isMin := false, mode := 14, alphaCoeff := 8, const := -12, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [148] },
    { rootMode := 26, nodeIndex := 141, isRoot := false, parentIndex := 138, isMin := false, mode := 23, alphaCoeff := 8, const := -12, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [149] },
    { rootMode := 26, nodeIndex := 142, isRoot := false, parentIndex := 114, isMin := false, mode := 14, alphaCoeff := 7, const := -13, status := 1, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 143, isRoot := false, parentIndex := 114, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [144, 145, 146] },
    { rootMode := 26, nodeIndex := 144, isRoot := false, parentIndex := 143, isMin := false, mode := 2, alphaCoeff := 8, const := -12, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [150, 151] },
    { rootMode := 26, nodeIndex := 145, isRoot := false, parentIndex := 143, isMin := false, mode := 11, alphaCoeff := 8, const := -12, status := 0, expansionDepth := 8, deletionAncestorIndex := 0, childIndices := [155, 156] },
    { rootMode := 26, nodeIndex := 146, isRoot := false, parentIndex := 143, isMin := false, mode := 20, alphaCoeff := 8, const := -12, status := 2, expansionDepth := 8, deletionAncestorIndex := 95, childIndices := [] },
    { rootMode := 26, nodeIndex := 147, isRoot := false, parentIndex := 139, isMin := false, mode := 20, alphaCoeff := 8, const := -14, status := 1, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 148, isRoot := false, parentIndex := 140, isMin := false, mode := 2, alphaCoeff := 8, const := -14, status := 1, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 149, isRoot := false, parentIndex := 141, isMin := false, mode := 11, alphaCoeff := 8, const := -14, status := 1, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 150, isRoot := false, parentIndex := 144, isMin := false, mode := 8, alphaCoeff := 8, const := -14, status := 1, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 151, isRoot := false, parentIndex := 144, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [152, 153, 154] },
    { rootMode := 26, nodeIndex := 152, isRoot := false, parentIndex := 151, isMin := false, mode := 2, alphaCoeff := 9, const := -14, status := 0, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [160, 161] },
    { rootMode := 26, nodeIndex := 153, isRoot := false, parentIndex := 151, isMin := false, mode := 11, alphaCoeff := 9, const := -14, status := 0, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [165, 166] },
    { rootMode := 26, nodeIndex := 154, isRoot := false, parentIndex := 151, isMin := false, mode := 20, alphaCoeff := 9, const := -14, status := 0, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [170, 171] },
    { rootMode := 26, nodeIndex := 155, isRoot := false, parentIndex := 145, isMin := false, mode := 17, alphaCoeff := 8, const := -14, status := 1, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 156, isRoot := false, parentIndex := 145, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [157, 158, 159] },
    { rootMode := 26, nodeIndex := 157, isRoot := false, parentIndex := 156, isMin := false, mode := 5, alphaCoeff := 9, const := -14, status := 0, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [175] },
    { rootMode := 26, nodeIndex := 158, isRoot := false, parentIndex := 156, isMin := false, mode := 14, alphaCoeff := 9, const := -14, status := 0, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [176] },
    { rootMode := 26, nodeIndex := 159, isRoot := false, parentIndex := 156, isMin := false, mode := 23, alphaCoeff := 9, const := -14, status := 0, expansionDepth := 9, deletionAncestorIndex := 0, childIndices := [177] },
    { rootMode := 26, nodeIndex := 160, isRoot := false, parentIndex := 152, isMin := false, mode := 8, alphaCoeff := 9, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 161, isRoot := false, parentIndex := 152, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [162, 163, 164] },
    { rootMode := 26, nodeIndex := 162, isRoot := false, parentIndex := 161, isMin := false, mode := 2, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 163, isRoot := false, parentIndex := 161, isMin := false, mode := 11, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 164, isRoot := false, parentIndex := 161, isMin := false, mode := 20, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 165, isRoot := false, parentIndex := 153, isMin := false, mode := 17, alphaCoeff := 9, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 166, isRoot := false, parentIndex := 153, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [167, 168, 169] },
    { rootMode := 26, nodeIndex := 167, isRoot := false, parentIndex := 166, isMin := false, mode := 5, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 168, isRoot := false, parentIndex := 166, isMin := false, mode := 14, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 169, isRoot := false, parentIndex := 166, isMin := false, mode := 23, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 170, isRoot := false, parentIndex := 154, isMin := false, mode := 26, alphaCoeff := 9, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 171, isRoot := false, parentIndex := 154, isMin := true, mode := 0, alphaCoeff := 0, const := 0, status := 0, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [172, 173, 174] },
    { rootMode := 26, nodeIndex := 172, isRoot := false, parentIndex := 171, isMin := false, mode := 8, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 173, isRoot := false, parentIndex := 171, isMin := false, mode := 17, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 174, isRoot := false, parentIndex := 171, isMin := false, mode := 26, alphaCoeff := 10, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 175, isRoot := false, parentIndex := 157, isMin := false, mode := 20, alphaCoeff := 9, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 176, isRoot := false, parentIndex := 158, isMin := false, mode := 2, alphaCoeff := 9, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] },
    { rootMode := 26, nodeIndex := 177, isRoot := false, parentIndex := 159, isMin := false, mode := 11, alphaCoeff := 9, const := -16, status := 1, expansionDepth := 10, deletionAncestorIndex := 0, childIndices := [] }
  ]

def treeNodes : List TreeNodeData :=
  treeNodes8.toList ++ treeNodes17.toList ++ treeNodes26.toList

end CollatzClassical.KL2003.GeneratedK3
