-- generated k2 row22 data; not imported; verifier not yet written
-- Generated by scripts/kl2003_f2_k2_row22_microgenerator_v1.py
-- Schema: KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2
-- Mode: rule_derived_row22
-- Scope: k2_row22_only
-- This file contains data declarations only and no mathematical theorem.

namespace KL2003F2K2Row22Generated

def schemaVersion : String := "KL2003_F2_HIGH_K_DATA_CERTIFICATE_FORMAT_v2"
def generationMode : String := "rule_derived_row22"
def scope : String := "k2_row22_only"
def proofStatus : String := "data_candidate_only"

def k : Nat := 2
def trackedClassCount : Nat := 3
def preReductionClassCount : Nat := 9

def rowId : String := "row22"
def sourceResidueMod9 : Nat := 2
def retardedChildFormula : String := "4*a"
def retardedChildResidueMod9 : Nat := 8
def advancedChildFormula : String := "c = 6*t + 1"
def advancedChildTracked : Bool := false
def liftedChildFormula : String := "2*c = 12*t + 2"
def liftedResidueTargets : List Nat := [2, 5, 8]
def parityLiftRoute : List String := ["2*c -> c", "c -> a"]
def rowShape : String :=
  "phi28(y - 2) + min3(phi22,phi25,phi28)(y + shiftAlphaMinus2Pad) <= phi22(y)"
def proofClaim : Bool := false

def constantIds : List String := ["lambda", "DeltaV2", "c22", "c25", "c28", "L2NT_D1_slack"]
def constantValues : List String := ["27/20", "(20/27)^14/2", "73/40", "1001/1000", "69/40", "29/9720"]

-- Candidate data only.  A future verifier must prove residue, route, parity
-- lift, window, min3 transfer, and slack obligations before any theorem may
-- consume this generated data.

end KL2003F2K2Row22Generated
