import CollatzClassical.KL2003.F3ReturnExcursionBlock0ReverseBFSCompleteness
import Lean.Meta.Basic
import Lean.Util.CollectAxioms

set_option maxRecDepth 100000

/-!
Fail-hard trust audit for the Block0 reverse-BFS completeness consequences.

The six explicit roots exhaust the public source-level theorems in
`F3ReturnExcursionBlock0ReverseBFSCompleteness`.  The namespace sweep also
checks any declarations generated by elaboration.  Compilation fails if a
declaration is missing or if any dependency cone contains an axiom other than
`propext`, `Classical.choice`, or `Quot.sound`.

This source records the audit contract only; it does not assert that the audit
has been compiled.
-/

namespace CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness

#print axioms firstHitViaChildAt_mem_of_reverse_closed
#print axioms verified_target_mem_nodeValues
#print axioms verified_deficient_orderedFirstHitFiber0_subset
#print axioms verified_deficient_orderedFirstHitFiber0_eq
#print axioms verified_deficient_fiber_card_eq_nodes_length
#print axioms verified_deficient_fiber_card_lt_demand

end CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness

namespace CollatzClassical.KL2003.F3Block0ReverseBFSCompletenessAudit

private def explicitRoots : Array Lean.Name := #[
  `CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness.firstHitViaChildAt_mem_of_reverse_closed,
  `CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness.verified_target_mem_nodeValues,
  `CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness.verified_deficient_orderedFirstHitFiber0_subset,
  `CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness.verified_deficient_orderedFirstHitFiber0_eq,
  `CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness.verified_deficient_fiber_card_eq_nodes_length,
  `CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness.verified_deficient_fiber_card_lt_demand
]

private def allowedAxiomNames : Lean.NameSet :=
  ({} : Lean.NameSet)
    |>.insert `propext
    |>.insert `Classical.choice
    |>.insert `Quot.sound

private def auditDeclaration
    (environment : Lean.Environment)
    (root : Lean.Name)
    (label : String) : Lean.MetaM Bool := do
  if (environment.checked.get.find? root).isNone then
    Lean.logError m!"{label}_DECLARATION_MISSING\t{root}"
    return true
  let (_, state) := ((Lean.CollectAxioms.collect root).run environment).run {}
  let axioms := state.axioms
  Lean.logInfo m!"{label}_AXIOM_PROFILE\t{root}\t{axioms.toList}"
  let unexpected := axioms.filter fun axiomName =>
    !allowedAxiomNames.contains axiomName
  if unexpected.isEmpty then
    return false
  Lean.logError m!"UNEXPECTED_{label}_AXIOM\troot={root}\thits={unexpected}"
  return true

run_meta do
  let environment ← Lean.getEnv
  let mut failed := false

  if explicitRoots.size != 6 then
    Lean.throwError
      m!"explicit reverse-BFS completeness inventory has {explicitRoots.size} entries; expected 6"

  for root in explicitRoots do
    if ← auditDeclaration environment root "EXPLICIT" then
      failed := true
  Lean.logInfo m!"EXPLICIT_DECLARATION_COVERAGE={explicitRoots.size}/6"

  let namespacePrefix :=
    `CollatzClassical.KL2003.F3Block0ReverseBFSCompleteness
  let declarations :=
    environment.constants.toList.map Prod.fst |>.filter namespacePrefix.isPrefixOf
  if declarations.length < explicitRoots.size then
    Lean.logError
      m!"NAMESPACE_INVENTORY_TOO_SMALL\tactual={declarations.length}\tminimum={explicitRoots.size}"
    failed := true
  for declaration in declarations do
    if ← auditDeclaration environment declaration "NAMESPACE" then
      failed := true
  Lean.logInfo
    m!"NAMESPACE_DECLARATION_COVERAGE={declarations.length}/{declarations.length}"

  if failed then
    Lean.throwError "Block0 reverse-BFS completeness trust audit failed"
  else
    Lean.logInfo "BLOCK0_REVERSE_BFS_COMPLETENESS_AUDIT_PASS"

end CollatzClassical.KL2003.F3Block0ReverseBFSCompletenessAudit
