import Mathlib

set_option maxRecDepth 100000

/-!
Exact finite representation of the frozen 243-state F3 core in `Real`.

The matrix entries use exact channel expressions with `Real.rpow`; no decimal
float is promoted to an equality.  The member-wise inequality is deliberately
left as a separate certificate obligation.
-/

noncomputable section
open scoped BigOperators

namespace CollatzClassical
namespace KL2003
namespace F3ExactCoreMatrix

structure CoreEdge where
  source : Fin 243
  target : Fin 243
  channel : Nat
  deriving DecidableEq, Repr

def coreEdges : List CoreEdge :=
  [
    { source := ⟨0, by decide⟩, target := ⟨8, by decide⟩, channel := 0 },
    { source := ⟨0, by decide⟩, target := ⟨1, by decide⟩, channel := 2 },
    { source := ⟨0, by decide⟩, target := ⟨82, by decide⟩, channel := 2 },
    { source := ⟨0, by decide⟩, target := ⟨163, by decide⟩, channel := 2 },
    { source := ⟨1, by decide⟩, target := ⟨8, by decide⟩, channel := 0 },
    { source := ⟨1, by decide⟩, target := ⟨1, by decide⟩, channel := 2 },
    { source := ⟨1, by decide⟩, target := ⟨82, by decide⟩, channel := 2 },
    { source := ⟨1, by decide⟩, target := ⟨163, by decide⟩, channel := 2 },
    { source := ⟨2, by decide⟩, target := ⟨8, by decide⟩, channel := 0 },
    { source := ⟨2, by decide⟩, target := ⟨1, by decide⟩, channel := 2 },
    { source := ⟨2, by decide⟩, target := ⟨82, by decide⟩, channel := 2 },
    { source := ⟨2, by decide⟩, target := ⟨163, by decide⟩, channel := 2 },
    { source := ⟨3, by decide⟩, target := ⟨20, by decide⟩, channel := 0 },
    { source := ⟨4, by decide⟩, target := ⟨20, by decide⟩, channel := 0 },
    { source := ⟨5, by decide⟩, target := ⟨20, by decide⟩, channel := 0 },
    { source := ⟨6, by decide⟩, target := ⟨32, by decide⟩, channel := 0 },
    { source := ⟨6, by decide⟩, target := ⟨3, by decide⟩, channel := 1 },
    { source := ⟨6, by decide⟩, target := ⟨165, by decide⟩, channel := 1 },
    { source := ⟨6, by decide⟩, target := ⟨84, by decide⟩, channel := 1 },
    { source := ⟨7, by decide⟩, target := ⟨32, by decide⟩, channel := 0 },
    { source := ⟨7, by decide⟩, target := ⟨3, by decide⟩, channel := 1 },
    { source := ⟨7, by decide⟩, target := ⟨165, by decide⟩, channel := 1 },
    { source := ⟨7, by decide⟩, target := ⟨84, by decide⟩, channel := 1 },
    { source := ⟨8, by decide⟩, target := ⟨32, by decide⟩, channel := 0 },
    { source := ⟨8, by decide⟩, target := ⟨3, by decide⟩, channel := 1 },
    { source := ⟨8, by decide⟩, target := ⟨165, by decide⟩, channel := 1 },
    { source := ⟨8, by decide⟩, target := ⟨84, by decide⟩, channel := 1 },
    { source := ⟨9, by decide⟩, target := ⟨44, by decide⟩, channel := 0 },
    { source := ⟨9, by decide⟩, target := ⟨13, by decide⟩, channel := 2 },
    { source := ⟨9, by decide⟩, target := ⟨94, by decide⟩, channel := 2 },
    { source := ⟨9, by decide⟩, target := ⟨175, by decide⟩, channel := 2 },
    { source := ⟨10, by decide⟩, target := ⟨44, by decide⟩, channel := 0 },
    { source := ⟨10, by decide⟩, target := ⟨13, by decide⟩, channel := 2 },
    { source := ⟨10, by decide⟩, target := ⟨94, by decide⟩, channel := 2 },
    { source := ⟨10, by decide⟩, target := ⟨175, by decide⟩, channel := 2 },
    { source := ⟨11, by decide⟩, target := ⟨44, by decide⟩, channel := 0 },
    { source := ⟨11, by decide⟩, target := ⟨13, by decide⟩, channel := 2 },
    { source := ⟨11, by decide⟩, target := ⟨94, by decide⟩, channel := 2 },
    { source := ⟨11, by decide⟩, target := ⟨175, by decide⟩, channel := 2 },
    { source := ⟨12, by decide⟩, target := ⟨56, by decide⟩, channel := 0 },
    { source := ⟨13, by decide⟩, target := ⟨56, by decide⟩, channel := 0 },
    { source := ⟨14, by decide⟩, target := ⟨56, by decide⟩, channel := 0 },
    { source := ⟨15, by decide⟩, target := ⟨68, by decide⟩, channel := 0 },
    { source := ⟨15, by decide⟩, target := ⟨9, by decide⟩, channel := 1 },
    { source := ⟨15, by decide⟩, target := ⟨171, by decide⟩, channel := 1 },
    { source := ⟨15, by decide⟩, target := ⟨90, by decide⟩, channel := 1 },
    { source := ⟨16, by decide⟩, target := ⟨68, by decide⟩, channel := 0 },
    { source := ⟨16, by decide⟩, target := ⟨9, by decide⟩, channel := 1 },
    { source := ⟨16, by decide⟩, target := ⟨171, by decide⟩, channel := 1 },
    { source := ⟨16, by decide⟩, target := ⟨90, by decide⟩, channel := 1 },
    { source := ⟨17, by decide⟩, target := ⟨68, by decide⟩, channel := 0 },
    { source := ⟨17, by decide⟩, target := ⟨9, by decide⟩, channel := 1 },
    { source := ⟨17, by decide⟩, target := ⟨171, by decide⟩, channel := 1 },
    { source := ⟨17, by decide⟩, target := ⟨90, by decide⟩, channel := 1 },
    { source := ⟨18, by decide⟩, target := ⟨80, by decide⟩, channel := 0 },
    { source := ⟨18, by decide⟩, target := ⟨25, by decide⟩, channel := 2 },
    { source := ⟨18, by decide⟩, target := ⟨106, by decide⟩, channel := 2 },
    { source := ⟨18, by decide⟩, target := ⟨187, by decide⟩, channel := 2 },
    { source := ⟨19, by decide⟩, target := ⟨80, by decide⟩, channel := 0 },
    { source := ⟨19, by decide⟩, target := ⟨25, by decide⟩, channel := 2 },
    { source := ⟨19, by decide⟩, target := ⟨106, by decide⟩, channel := 2 },
    { source := ⟨19, by decide⟩, target := ⟨187, by decide⟩, channel := 2 },
    { source := ⟨20, by decide⟩, target := ⟨80, by decide⟩, channel := 0 },
    { source := ⟨20, by decide⟩, target := ⟨25, by decide⟩, channel := 2 },
    { source := ⟨20, by decide⟩, target := ⟨106, by decide⟩, channel := 2 },
    { source := ⟨20, by decide⟩, target := ⟨187, by decide⟩, channel := 2 },
    { source := ⟨21, by decide⟩, target := ⟨92, by decide⟩, channel := 0 },
    { source := ⟨22, by decide⟩, target := ⟨92, by decide⟩, channel := 0 },
    { source := ⟨23, by decide⟩, target := ⟨92, by decide⟩, channel := 0 },
    { source := ⟨24, by decide⟩, target := ⟨104, by decide⟩, channel := 0 },
    { source := ⟨24, by decide⟩, target := ⟨15, by decide⟩, channel := 1 },
    { source := ⟨24, by decide⟩, target := ⟨177, by decide⟩, channel := 1 },
    { source := ⟨24, by decide⟩, target := ⟨96, by decide⟩, channel := 1 },
    { source := ⟨25, by decide⟩, target := ⟨104, by decide⟩, channel := 0 },
    { source := ⟨25, by decide⟩, target := ⟨15, by decide⟩, channel := 1 },
    { source := ⟨25, by decide⟩, target := ⟨177, by decide⟩, channel := 1 },
    { source := ⟨25, by decide⟩, target := ⟨96, by decide⟩, channel := 1 },
    { source := ⟨26, by decide⟩, target := ⟨104, by decide⟩, channel := 0 },
    { source := ⟨26, by decide⟩, target := ⟨15, by decide⟩, channel := 1 },
    { source := ⟨26, by decide⟩, target := ⟨177, by decide⟩, channel := 1 },
    { source := ⟨26, by decide⟩, target := ⟨96, by decide⟩, channel := 1 },
    { source := ⟨27, by decide⟩, target := ⟨116, by decide⟩, channel := 0 },
    { source := ⟨27, by decide⟩, target := ⟨37, by decide⟩, channel := 2 },
    { source := ⟨27, by decide⟩, target := ⟨118, by decide⟩, channel := 2 },
    { source := ⟨27, by decide⟩, target := ⟨199, by decide⟩, channel := 2 },
    { source := ⟨28, by decide⟩, target := ⟨116, by decide⟩, channel := 0 },
    { source := ⟨28, by decide⟩, target := ⟨37, by decide⟩, channel := 2 },
    { source := ⟨28, by decide⟩, target := ⟨118, by decide⟩, channel := 2 },
    { source := ⟨28, by decide⟩, target := ⟨199, by decide⟩, channel := 2 },
    { source := ⟨29, by decide⟩, target := ⟨116, by decide⟩, channel := 0 },
    { source := ⟨29, by decide⟩, target := ⟨37, by decide⟩, channel := 2 },
    { source := ⟨29, by decide⟩, target := ⟨118, by decide⟩, channel := 2 },
    { source := ⟨29, by decide⟩, target := ⟨199, by decide⟩, channel := 2 },
    { source := ⟨30, by decide⟩, target := ⟨128, by decide⟩, channel := 0 },
    { source := ⟨31, by decide⟩, target := ⟨128, by decide⟩, channel := 0 },
    { source := ⟨32, by decide⟩, target := ⟨128, by decide⟩, channel := 0 },
    { source := ⟨33, by decide⟩, target := ⟨140, by decide⟩, channel := 0 },
    { source := ⟨33, by decide⟩, target := ⟨21, by decide⟩, channel := 1 },
    { source := ⟨33, by decide⟩, target := ⟨183, by decide⟩, channel := 1 },
    { source := ⟨33, by decide⟩, target := ⟨102, by decide⟩, channel := 1 },
    { source := ⟨34, by decide⟩, target := ⟨140, by decide⟩, channel := 0 },
    { source := ⟨34, by decide⟩, target := ⟨21, by decide⟩, channel := 1 },
    { source := ⟨34, by decide⟩, target := ⟨183, by decide⟩, channel := 1 },
    { source := ⟨34, by decide⟩, target := ⟨102, by decide⟩, channel := 1 },
    { source := ⟨35, by decide⟩, target := ⟨140, by decide⟩, channel := 0 },
    { source := ⟨35, by decide⟩, target := ⟨21, by decide⟩, channel := 1 },
    { source := ⟨35, by decide⟩, target := ⟨183, by decide⟩, channel := 1 },
    { source := ⟨35, by decide⟩, target := ⟨102, by decide⟩, channel := 1 },
    { source := ⟨36, by decide⟩, target := ⟨152, by decide⟩, channel := 0 },
    { source := ⟨36, by decide⟩, target := ⟨49, by decide⟩, channel := 2 },
    { source := ⟨36, by decide⟩, target := ⟨130, by decide⟩, channel := 2 },
    { source := ⟨36, by decide⟩, target := ⟨211, by decide⟩, channel := 2 },
    { source := ⟨37, by decide⟩, target := ⟨152, by decide⟩, channel := 0 },
    { source := ⟨37, by decide⟩, target := ⟨49, by decide⟩, channel := 2 },
    { source := ⟨37, by decide⟩, target := ⟨130, by decide⟩, channel := 2 },
    { source := ⟨37, by decide⟩, target := ⟨211, by decide⟩, channel := 2 },
    { source := ⟨38, by decide⟩, target := ⟨152, by decide⟩, channel := 0 },
    { source := ⟨38, by decide⟩, target := ⟨49, by decide⟩, channel := 2 },
    { source := ⟨38, by decide⟩, target := ⟨130, by decide⟩, channel := 2 },
    { source := ⟨38, by decide⟩, target := ⟨211, by decide⟩, channel := 2 },
    { source := ⟨39, by decide⟩, target := ⟨164, by decide⟩, channel := 0 },
    { source := ⟨40, by decide⟩, target := ⟨164, by decide⟩, channel := 0 },
    { source := ⟨41, by decide⟩, target := ⟨164, by decide⟩, channel := 0 },
    { source := ⟨42, by decide⟩, target := ⟨176, by decide⟩, channel := 0 },
    { source := ⟨42, by decide⟩, target := ⟨27, by decide⟩, channel := 1 },
    { source := ⟨42, by decide⟩, target := ⟨189, by decide⟩, channel := 1 },
    { source := ⟨42, by decide⟩, target := ⟨108, by decide⟩, channel := 1 },
    { source := ⟨43, by decide⟩, target := ⟨176, by decide⟩, channel := 0 },
    { source := ⟨43, by decide⟩, target := ⟨27, by decide⟩, channel := 1 },
    { source := ⟨43, by decide⟩, target := ⟨189, by decide⟩, channel := 1 },
    { source := ⟨43, by decide⟩, target := ⟨108, by decide⟩, channel := 1 },
    { source := ⟨44, by decide⟩, target := ⟨176, by decide⟩, channel := 0 },
    { source := ⟨44, by decide⟩, target := ⟨27, by decide⟩, channel := 1 },
    { source := ⟨44, by decide⟩, target := ⟨189, by decide⟩, channel := 1 },
    { source := ⟨44, by decide⟩, target := ⟨108, by decide⟩, channel := 1 },
    { source := ⟨45, by decide⟩, target := ⟨188, by decide⟩, channel := 0 },
    { source := ⟨45, by decide⟩, target := ⟨61, by decide⟩, channel := 2 },
    { source := ⟨45, by decide⟩, target := ⟨142, by decide⟩, channel := 2 },
    { source := ⟨45, by decide⟩, target := ⟨223, by decide⟩, channel := 2 },
    { source := ⟨46, by decide⟩, target := ⟨188, by decide⟩, channel := 0 },
    { source := ⟨46, by decide⟩, target := ⟨61, by decide⟩, channel := 2 },
    { source := ⟨46, by decide⟩, target := ⟨142, by decide⟩, channel := 2 },
    { source := ⟨46, by decide⟩, target := ⟨223, by decide⟩, channel := 2 },
    { source := ⟨47, by decide⟩, target := ⟨188, by decide⟩, channel := 0 },
    { source := ⟨47, by decide⟩, target := ⟨61, by decide⟩, channel := 2 },
    { source := ⟨47, by decide⟩, target := ⟨142, by decide⟩, channel := 2 },
    { source := ⟨47, by decide⟩, target := ⟨223, by decide⟩, channel := 2 },
    { source := ⟨48, by decide⟩, target := ⟨200, by decide⟩, channel := 0 },
    { source := ⟨49, by decide⟩, target := ⟨200, by decide⟩, channel := 0 },
    { source := ⟨50, by decide⟩, target := ⟨200, by decide⟩, channel := 0 },
    { source := ⟨51, by decide⟩, target := ⟨212, by decide⟩, channel := 0 },
    { source := ⟨51, by decide⟩, target := ⟨33, by decide⟩, channel := 1 },
    { source := ⟨51, by decide⟩, target := ⟨195, by decide⟩, channel := 1 },
    { source := ⟨51, by decide⟩, target := ⟨114, by decide⟩, channel := 1 },
    { source := ⟨52, by decide⟩, target := ⟨212, by decide⟩, channel := 0 },
    { source := ⟨52, by decide⟩, target := ⟨33, by decide⟩, channel := 1 },
    { source := ⟨52, by decide⟩, target := ⟨195, by decide⟩, channel := 1 },
    { source := ⟨52, by decide⟩, target := ⟨114, by decide⟩, channel := 1 },
    { source := ⟨53, by decide⟩, target := ⟨212, by decide⟩, channel := 0 },
    { source := ⟨53, by decide⟩, target := ⟨33, by decide⟩, channel := 1 },
    { source := ⟨53, by decide⟩, target := ⟨195, by decide⟩, channel := 1 },
    { source := ⟨53, by decide⟩, target := ⟨114, by decide⟩, channel := 1 },
    { source := ⟨54, by decide⟩, target := ⟨224, by decide⟩, channel := 0 },
    { source := ⟨54, by decide⟩, target := ⟨73, by decide⟩, channel := 2 },
    { source := ⟨54, by decide⟩, target := ⟨154, by decide⟩, channel := 2 },
    { source := ⟨54, by decide⟩, target := ⟨235, by decide⟩, channel := 2 },
    { source := ⟨55, by decide⟩, target := ⟨224, by decide⟩, channel := 0 },
    { source := ⟨55, by decide⟩, target := ⟨73, by decide⟩, channel := 2 },
    { source := ⟨55, by decide⟩, target := ⟨154, by decide⟩, channel := 2 },
    { source := ⟨55, by decide⟩, target := ⟨235, by decide⟩, channel := 2 },
    { source := ⟨56, by decide⟩, target := ⟨224, by decide⟩, channel := 0 },
    { source := ⟨56, by decide⟩, target := ⟨73, by decide⟩, channel := 2 },
    { source := ⟨56, by decide⟩, target := ⟨154, by decide⟩, channel := 2 },
    { source := ⟨56, by decide⟩, target := ⟨235, by decide⟩, channel := 2 },
    { source := ⟨57, by decide⟩, target := ⟨236, by decide⟩, channel := 0 },
    { source := ⟨58, by decide⟩, target := ⟨236, by decide⟩, channel := 0 },
    { source := ⟨59, by decide⟩, target := ⟨236, by decide⟩, channel := 0 },
    { source := ⟨60, by decide⟩, target := ⟨5, by decide⟩, channel := 0 },
    { source := ⟨60, by decide⟩, target := ⟨39, by decide⟩, channel := 1 },
    { source := ⟨60, by decide⟩, target := ⟨201, by decide⟩, channel := 1 },
    { source := ⟨60, by decide⟩, target := ⟨120, by decide⟩, channel := 1 },
    { source := ⟨61, by decide⟩, target := ⟨5, by decide⟩, channel := 0 },
    { source := ⟨61, by decide⟩, target := ⟨39, by decide⟩, channel := 1 },
    { source := ⟨61, by decide⟩, target := ⟨201, by decide⟩, channel := 1 },
    { source := ⟨61, by decide⟩, target := ⟨120, by decide⟩, channel := 1 },
    { source := ⟨62, by decide⟩, target := ⟨5, by decide⟩, channel := 0 },
    { source := ⟨62, by decide⟩, target := ⟨39, by decide⟩, channel := 1 },
    { source := ⟨62, by decide⟩, target := ⟨201, by decide⟩, channel := 1 },
    { source := ⟨62, by decide⟩, target := ⟨120, by decide⟩, channel := 1 },
    { source := ⟨63, by decide⟩, target := ⟨17, by decide⟩, channel := 0 },
    { source := ⟨63, by decide⟩, target := ⟨85, by decide⟩, channel := 2 },
    { source := ⟨63, by decide⟩, target := ⟨166, by decide⟩, channel := 2 },
    { source := ⟨63, by decide⟩, target := ⟨4, by decide⟩, channel := 2 },
    { source := ⟨64, by decide⟩, target := ⟨17, by decide⟩, channel := 0 },
    { source := ⟨64, by decide⟩, target := ⟨85, by decide⟩, channel := 2 },
    { source := ⟨64, by decide⟩, target := ⟨166, by decide⟩, channel := 2 },
    { source := ⟨64, by decide⟩, target := ⟨4, by decide⟩, channel := 2 },
    { source := ⟨65, by decide⟩, target := ⟨17, by decide⟩, channel := 0 },
    { source := ⟨65, by decide⟩, target := ⟨85, by decide⟩, channel := 2 },
    { source := ⟨65, by decide⟩, target := ⟨166, by decide⟩, channel := 2 },
    { source := ⟨65, by decide⟩, target := ⟨4, by decide⟩, channel := 2 },
    { source := ⟨66, by decide⟩, target := ⟨29, by decide⟩, channel := 0 },
    { source := ⟨67, by decide⟩, target := ⟨29, by decide⟩, channel := 0 },
    { source := ⟨68, by decide⟩, target := ⟨29, by decide⟩, channel := 0 },
    { source := ⟨69, by decide⟩, target := ⟨41, by decide⟩, channel := 0 },
    { source := ⟨69, by decide⟩, target := ⟨45, by decide⟩, channel := 1 },
    { source := ⟨69, by decide⟩, target := ⟨207, by decide⟩, channel := 1 },
    { source := ⟨69, by decide⟩, target := ⟨126, by decide⟩, channel := 1 },
    { source := ⟨70, by decide⟩, target := ⟨41, by decide⟩, channel := 0 },
    { source := ⟨70, by decide⟩, target := ⟨45, by decide⟩, channel := 1 },
    { source := ⟨70, by decide⟩, target := ⟨207, by decide⟩, channel := 1 },
    { source := ⟨70, by decide⟩, target := ⟨126, by decide⟩, channel := 1 },
    { source := ⟨71, by decide⟩, target := ⟨41, by decide⟩, channel := 0 },
    { source := ⟨71, by decide⟩, target := ⟨45, by decide⟩, channel := 1 },
    { source := ⟨71, by decide⟩, target := ⟨207, by decide⟩, channel := 1 },
    { source := ⟨71, by decide⟩, target := ⟨126, by decide⟩, channel := 1 },
    { source := ⟨72, by decide⟩, target := ⟨53, by decide⟩, channel := 0 },
    { source := ⟨72, by decide⟩, target := ⟨97, by decide⟩, channel := 2 },
    { source := ⟨72, by decide⟩, target := ⟨178, by decide⟩, channel := 2 },
    { source := ⟨72, by decide⟩, target := ⟨16, by decide⟩, channel := 2 },
    { source := ⟨73, by decide⟩, target := ⟨53, by decide⟩, channel := 0 },
    { source := ⟨73, by decide⟩, target := ⟨97, by decide⟩, channel := 2 },
    { source := ⟨73, by decide⟩, target := ⟨178, by decide⟩, channel := 2 },
    { source := ⟨73, by decide⟩, target := ⟨16, by decide⟩, channel := 2 },
    { source := ⟨74, by decide⟩, target := ⟨53, by decide⟩, channel := 0 },
    { source := ⟨74, by decide⟩, target := ⟨97, by decide⟩, channel := 2 },
    { source := ⟨74, by decide⟩, target := ⟨178, by decide⟩, channel := 2 },
    { source := ⟨74, by decide⟩, target := ⟨16, by decide⟩, channel := 2 },
    { source := ⟨75, by decide⟩, target := ⟨65, by decide⟩, channel := 0 },
    { source := ⟨76, by decide⟩, target := ⟨65, by decide⟩, channel := 0 },
    { source := ⟨77, by decide⟩, target := ⟨65, by decide⟩, channel := 0 },
    { source := ⟨78, by decide⟩, target := ⟨77, by decide⟩, channel := 0 },
    { source := ⟨78, by decide⟩, target := ⟨51, by decide⟩, channel := 1 },
    { source := ⟨78, by decide⟩, target := ⟨213, by decide⟩, channel := 1 },
    { source := ⟨78, by decide⟩, target := ⟨132, by decide⟩, channel := 1 },
    { source := ⟨79, by decide⟩, target := ⟨77, by decide⟩, channel := 0 },
    { source := ⟨79, by decide⟩, target := ⟨51, by decide⟩, channel := 1 },
    { source := ⟨79, by decide⟩, target := ⟨213, by decide⟩, channel := 1 },
    { source := ⟨79, by decide⟩, target := ⟨132, by decide⟩, channel := 1 },
    { source := ⟨80, by decide⟩, target := ⟨77, by decide⟩, channel := 0 },
    { source := ⟨80, by decide⟩, target := ⟨51, by decide⟩, channel := 1 },
    { source := ⟨80, by decide⟩, target := ⟨213, by decide⟩, channel := 1 },
    { source := ⟨80, by decide⟩, target := ⟨132, by decide⟩, channel := 1 },
    { source := ⟨81, by decide⟩, target := ⟨89, by decide⟩, channel := 0 },
    { source := ⟨81, by decide⟩, target := ⟨109, by decide⟩, channel := 2 },
    { source := ⟨81, by decide⟩, target := ⟨190, by decide⟩, channel := 2 },
    { source := ⟨81, by decide⟩, target := ⟨28, by decide⟩, channel := 2 },
    { source := ⟨82, by decide⟩, target := ⟨89, by decide⟩, channel := 0 },
    { source := ⟨82, by decide⟩, target := ⟨109, by decide⟩, channel := 2 },
    { source := ⟨82, by decide⟩, target := ⟨190, by decide⟩, channel := 2 },
    { source := ⟨82, by decide⟩, target := ⟨28, by decide⟩, channel := 2 },
    { source := ⟨83, by decide⟩, target := ⟨89, by decide⟩, channel := 0 },
    { source := ⟨83, by decide⟩, target := ⟨109, by decide⟩, channel := 2 },
    { source := ⟨83, by decide⟩, target := ⟨190, by decide⟩, channel := 2 },
    { source := ⟨83, by decide⟩, target := ⟨28, by decide⟩, channel := 2 },
    { source := ⟨84, by decide⟩, target := ⟨101, by decide⟩, channel := 0 },
    { source := ⟨85, by decide⟩, target := ⟨101, by decide⟩, channel := 0 },
    { source := ⟨86, by decide⟩, target := ⟨101, by decide⟩, channel := 0 },
    { source := ⟨87, by decide⟩, target := ⟨113, by decide⟩, channel := 0 },
    { source := ⟨87, by decide⟩, target := ⟨57, by decide⟩, channel := 1 },
    { source := ⟨87, by decide⟩, target := ⟨219, by decide⟩, channel := 1 },
    { source := ⟨87, by decide⟩, target := ⟨138, by decide⟩, channel := 1 },
    { source := ⟨88, by decide⟩, target := ⟨113, by decide⟩, channel := 0 },
    { source := ⟨88, by decide⟩, target := ⟨57, by decide⟩, channel := 1 },
    { source := ⟨88, by decide⟩, target := ⟨219, by decide⟩, channel := 1 },
    { source := ⟨88, by decide⟩, target := ⟨138, by decide⟩, channel := 1 },
    { source := ⟨89, by decide⟩, target := ⟨113, by decide⟩, channel := 0 },
    { source := ⟨89, by decide⟩, target := ⟨57, by decide⟩, channel := 1 },
    { source := ⟨89, by decide⟩, target := ⟨219, by decide⟩, channel := 1 },
    { source := ⟨89, by decide⟩, target := ⟨138, by decide⟩, channel := 1 },
    { source := ⟨90, by decide⟩, target := ⟨125, by decide⟩, channel := 0 },
    { source := ⟨90, by decide⟩, target := ⟨121, by decide⟩, channel := 2 },
    { source := ⟨90, by decide⟩, target := ⟨202, by decide⟩, channel := 2 },
    { source := ⟨90, by decide⟩, target := ⟨40, by decide⟩, channel := 2 },
    { source := ⟨91, by decide⟩, target := ⟨125, by decide⟩, channel := 0 },
    { source := ⟨91, by decide⟩, target := ⟨121, by decide⟩, channel := 2 },
    { source := ⟨91, by decide⟩, target := ⟨202, by decide⟩, channel := 2 },
    { source := ⟨91, by decide⟩, target := ⟨40, by decide⟩, channel := 2 },
    { source := ⟨92, by decide⟩, target := ⟨125, by decide⟩, channel := 0 },
    { source := ⟨92, by decide⟩, target := ⟨121, by decide⟩, channel := 2 },
    { source := ⟨92, by decide⟩, target := ⟨202, by decide⟩, channel := 2 },
    { source := ⟨92, by decide⟩, target := ⟨40, by decide⟩, channel := 2 },
    { source := ⟨93, by decide⟩, target := ⟨137, by decide⟩, channel := 0 },
    { source := ⟨94, by decide⟩, target := ⟨137, by decide⟩, channel := 0 },
    { source := ⟨95, by decide⟩, target := ⟨137, by decide⟩, channel := 0 },
    { source := ⟨96, by decide⟩, target := ⟨149, by decide⟩, channel := 0 },
    { source := ⟨96, by decide⟩, target := ⟨63, by decide⟩, channel := 1 },
    { source := ⟨96, by decide⟩, target := ⟨225, by decide⟩, channel := 1 },
    { source := ⟨96, by decide⟩, target := ⟨144, by decide⟩, channel := 1 },
    { source := ⟨97, by decide⟩, target := ⟨149, by decide⟩, channel := 0 },
    { source := ⟨97, by decide⟩, target := ⟨63, by decide⟩, channel := 1 },
    { source := ⟨97, by decide⟩, target := ⟨225, by decide⟩, channel := 1 },
    { source := ⟨97, by decide⟩, target := ⟨144, by decide⟩, channel := 1 },
    { source := ⟨98, by decide⟩, target := ⟨149, by decide⟩, channel := 0 },
    { source := ⟨98, by decide⟩, target := ⟨63, by decide⟩, channel := 1 },
    { source := ⟨98, by decide⟩, target := ⟨225, by decide⟩, channel := 1 },
    { source := ⟨98, by decide⟩, target := ⟨144, by decide⟩, channel := 1 },
    { source := ⟨99, by decide⟩, target := ⟨161, by decide⟩, channel := 0 },
    { source := ⟨99, by decide⟩, target := ⟨133, by decide⟩, channel := 2 },
    { source := ⟨99, by decide⟩, target := ⟨214, by decide⟩, channel := 2 },
    { source := ⟨99, by decide⟩, target := ⟨52, by decide⟩, channel := 2 },
    { source := ⟨100, by decide⟩, target := ⟨161, by decide⟩, channel := 0 },
    { source := ⟨100, by decide⟩, target := ⟨133, by decide⟩, channel := 2 },
    { source := ⟨100, by decide⟩, target := ⟨214, by decide⟩, channel := 2 },
    { source := ⟨100, by decide⟩, target := ⟨52, by decide⟩, channel := 2 },
    { source := ⟨101, by decide⟩, target := ⟨161, by decide⟩, channel := 0 },
    { source := ⟨101, by decide⟩, target := ⟨133, by decide⟩, channel := 2 },
    { source := ⟨101, by decide⟩, target := ⟨214, by decide⟩, channel := 2 },
    { source := ⟨101, by decide⟩, target := ⟨52, by decide⟩, channel := 2 },
    { source := ⟨102, by decide⟩, target := ⟨173, by decide⟩, channel := 0 },
    { source := ⟨103, by decide⟩, target := ⟨173, by decide⟩, channel := 0 },
    { source := ⟨104, by decide⟩, target := ⟨173, by decide⟩, channel := 0 },
    { source := ⟨105, by decide⟩, target := ⟨185, by decide⟩, channel := 0 },
    { source := ⟨105, by decide⟩, target := ⟨69, by decide⟩, channel := 1 },
    { source := ⟨105, by decide⟩, target := ⟨231, by decide⟩, channel := 1 },
    { source := ⟨105, by decide⟩, target := ⟨150, by decide⟩, channel := 1 },
    { source := ⟨106, by decide⟩, target := ⟨185, by decide⟩, channel := 0 },
    { source := ⟨106, by decide⟩, target := ⟨69, by decide⟩, channel := 1 },
    { source := ⟨106, by decide⟩, target := ⟨231, by decide⟩, channel := 1 },
    { source := ⟨106, by decide⟩, target := ⟨150, by decide⟩, channel := 1 },
    { source := ⟨107, by decide⟩, target := ⟨185, by decide⟩, channel := 0 },
    { source := ⟨107, by decide⟩, target := ⟨69, by decide⟩, channel := 1 },
    { source := ⟨107, by decide⟩, target := ⟨231, by decide⟩, channel := 1 },
    { source := ⟨107, by decide⟩, target := ⟨150, by decide⟩, channel := 1 },
    { source := ⟨108, by decide⟩, target := ⟨197, by decide⟩, channel := 0 },
    { source := ⟨108, by decide⟩, target := ⟨145, by decide⟩, channel := 2 },
    { source := ⟨108, by decide⟩, target := ⟨226, by decide⟩, channel := 2 },
    { source := ⟨108, by decide⟩, target := ⟨64, by decide⟩, channel := 2 },
    { source := ⟨109, by decide⟩, target := ⟨197, by decide⟩, channel := 0 },
    { source := ⟨109, by decide⟩, target := ⟨145, by decide⟩, channel := 2 },
    { source := ⟨109, by decide⟩, target := ⟨226, by decide⟩, channel := 2 },
    { source := ⟨109, by decide⟩, target := ⟨64, by decide⟩, channel := 2 },
    { source := ⟨110, by decide⟩, target := ⟨197, by decide⟩, channel := 0 },
    { source := ⟨110, by decide⟩, target := ⟨145, by decide⟩, channel := 2 },
    { source := ⟨110, by decide⟩, target := ⟨226, by decide⟩, channel := 2 },
    { source := ⟨110, by decide⟩, target := ⟨64, by decide⟩, channel := 2 },
    { source := ⟨111, by decide⟩, target := ⟨209, by decide⟩, channel := 0 },
    { source := ⟨112, by decide⟩, target := ⟨209, by decide⟩, channel := 0 },
    { source := ⟨113, by decide⟩, target := ⟨209, by decide⟩, channel := 0 },
    { source := ⟨114, by decide⟩, target := ⟨221, by decide⟩, channel := 0 },
    { source := ⟨114, by decide⟩, target := ⟨75, by decide⟩, channel := 1 },
    { source := ⟨114, by decide⟩, target := ⟨237, by decide⟩, channel := 1 },
    { source := ⟨114, by decide⟩, target := ⟨156, by decide⟩, channel := 1 },
    { source := ⟨115, by decide⟩, target := ⟨221, by decide⟩, channel := 0 },
    { source := ⟨115, by decide⟩, target := ⟨75, by decide⟩, channel := 1 },
    { source := ⟨115, by decide⟩, target := ⟨237, by decide⟩, channel := 1 },
    { source := ⟨115, by decide⟩, target := ⟨156, by decide⟩, channel := 1 },
    { source := ⟨116, by decide⟩, target := ⟨221, by decide⟩, channel := 0 },
    { source := ⟨116, by decide⟩, target := ⟨75, by decide⟩, channel := 1 },
    { source := ⟨116, by decide⟩, target := ⟨237, by decide⟩, channel := 1 },
    { source := ⟨116, by decide⟩, target := ⟨156, by decide⟩, channel := 1 },
    { source := ⟨117, by decide⟩, target := ⟨233, by decide⟩, channel := 0 },
    { source := ⟨117, by decide⟩, target := ⟨157, by decide⟩, channel := 2 },
    { source := ⟨117, by decide⟩, target := ⟨238, by decide⟩, channel := 2 },
    { source := ⟨117, by decide⟩, target := ⟨76, by decide⟩, channel := 2 },
    { source := ⟨118, by decide⟩, target := ⟨233, by decide⟩, channel := 0 },
    { source := ⟨118, by decide⟩, target := ⟨157, by decide⟩, channel := 2 },
    { source := ⟨118, by decide⟩, target := ⟨238, by decide⟩, channel := 2 },
    { source := ⟨118, by decide⟩, target := ⟨76, by decide⟩, channel := 2 },
    { source := ⟨119, by decide⟩, target := ⟨233, by decide⟩, channel := 0 },
    { source := ⟨119, by decide⟩, target := ⟨157, by decide⟩, channel := 2 },
    { source := ⟨119, by decide⟩, target := ⟨238, by decide⟩, channel := 2 },
    { source := ⟨119, by decide⟩, target := ⟨76, by decide⟩, channel := 2 },
    { source := ⟨120, by decide⟩, target := ⟨2, by decide⟩, channel := 0 },
    { source := ⟨121, by decide⟩, target := ⟨2, by decide⟩, channel := 0 },
    { source := ⟨122, by decide⟩, target := ⟨2, by decide⟩, channel := 0 },
    { source := ⟨123, by decide⟩, target := ⟨14, by decide⟩, channel := 0 },
    { source := ⟨123, by decide⟩, target := ⟨81, by decide⟩, channel := 1 },
    { source := ⟨123, by decide⟩, target := ⟨0, by decide⟩, channel := 1 },
    { source := ⟨123, by decide⟩, target := ⟨162, by decide⟩, channel := 1 },
    { source := ⟨124, by decide⟩, target := ⟨14, by decide⟩, channel := 0 },
    { source := ⟨124, by decide⟩, target := ⟨81, by decide⟩, channel := 1 },
    { source := ⟨124, by decide⟩, target := ⟨0, by decide⟩, channel := 1 },
    { source := ⟨124, by decide⟩, target := ⟨162, by decide⟩, channel := 1 },
    { source := ⟨125, by decide⟩, target := ⟨14, by decide⟩, channel := 0 },
    { source := ⟨125, by decide⟩, target := ⟨81, by decide⟩, channel := 1 },
    { source := ⟨125, by decide⟩, target := ⟨0, by decide⟩, channel := 1 },
    { source := ⟨125, by decide⟩, target := ⟨162, by decide⟩, channel := 1 },
    { source := ⟨126, by decide⟩, target := ⟨26, by decide⟩, channel := 0 },
    { source := ⟨126, by decide⟩, target := ⟨169, by decide⟩, channel := 2 },
    { source := ⟨126, by decide⟩, target := ⟨7, by decide⟩, channel := 2 },
    { source := ⟨126, by decide⟩, target := ⟨88, by decide⟩, channel := 2 },
    { source := ⟨127, by decide⟩, target := ⟨26, by decide⟩, channel := 0 },
    { source := ⟨127, by decide⟩, target := ⟨169, by decide⟩, channel := 2 },
    { source := ⟨127, by decide⟩, target := ⟨7, by decide⟩, channel := 2 },
    { source := ⟨127, by decide⟩, target := ⟨88, by decide⟩, channel := 2 },
    { source := ⟨128, by decide⟩, target := ⟨26, by decide⟩, channel := 0 },
    { source := ⟨128, by decide⟩, target := ⟨169, by decide⟩, channel := 2 },
    { source := ⟨128, by decide⟩, target := ⟨7, by decide⟩, channel := 2 },
    { source := ⟨128, by decide⟩, target := ⟨88, by decide⟩, channel := 2 },
    { source := ⟨129, by decide⟩, target := ⟨38, by decide⟩, channel := 0 },
    { source := ⟨130, by decide⟩, target := ⟨38, by decide⟩, channel := 0 },
    { source := ⟨131, by decide⟩, target := ⟨38, by decide⟩, channel := 0 },
    { source := ⟨132, by decide⟩, target := ⟨50, by decide⟩, channel := 0 },
    { source := ⟨132, by decide⟩, target := ⟨87, by decide⟩, channel := 1 },
    { source := ⟨132, by decide⟩, target := ⟨6, by decide⟩, channel := 1 },
    { source := ⟨132, by decide⟩, target := ⟨168, by decide⟩, channel := 1 },
    { source := ⟨133, by decide⟩, target := ⟨50, by decide⟩, channel := 0 },
    { source := ⟨133, by decide⟩, target := ⟨87, by decide⟩, channel := 1 },
    { source := ⟨133, by decide⟩, target := ⟨6, by decide⟩, channel := 1 },
    { source := ⟨133, by decide⟩, target := ⟨168, by decide⟩, channel := 1 },
    { source := ⟨134, by decide⟩, target := ⟨50, by decide⟩, channel := 0 },
    { source := ⟨134, by decide⟩, target := ⟨87, by decide⟩, channel := 1 },
    { source := ⟨134, by decide⟩, target := ⟨6, by decide⟩, channel := 1 },
    { source := ⟨134, by decide⟩, target := ⟨168, by decide⟩, channel := 1 },
    { source := ⟨135, by decide⟩, target := ⟨62, by decide⟩, channel := 0 },
    { source := ⟨135, by decide⟩, target := ⟨181, by decide⟩, channel := 2 },
    { source := ⟨135, by decide⟩, target := ⟨19, by decide⟩, channel := 2 },
    { source := ⟨135, by decide⟩, target := ⟨100, by decide⟩, channel := 2 },
    { source := ⟨136, by decide⟩, target := ⟨62, by decide⟩, channel := 0 },
    { source := ⟨136, by decide⟩, target := ⟨181, by decide⟩, channel := 2 },
    { source := ⟨136, by decide⟩, target := ⟨19, by decide⟩, channel := 2 },
    { source := ⟨136, by decide⟩, target := ⟨100, by decide⟩, channel := 2 },
    { source := ⟨137, by decide⟩, target := ⟨62, by decide⟩, channel := 0 },
    { source := ⟨137, by decide⟩, target := ⟨181, by decide⟩, channel := 2 },
    { source := ⟨137, by decide⟩, target := ⟨19, by decide⟩, channel := 2 },
    { source := ⟨137, by decide⟩, target := ⟨100, by decide⟩, channel := 2 },
    { source := ⟨138, by decide⟩, target := ⟨74, by decide⟩, channel := 0 },
    { source := ⟨139, by decide⟩, target := ⟨74, by decide⟩, channel := 0 },
    { source := ⟨140, by decide⟩, target := ⟨74, by decide⟩, channel := 0 },
    { source := ⟨141, by decide⟩, target := ⟨86, by decide⟩, channel := 0 },
    { source := ⟨141, by decide⟩, target := ⟨93, by decide⟩, channel := 1 },
    { source := ⟨141, by decide⟩, target := ⟨12, by decide⟩, channel := 1 },
    { source := ⟨141, by decide⟩, target := ⟨174, by decide⟩, channel := 1 },
    { source := ⟨142, by decide⟩, target := ⟨86, by decide⟩, channel := 0 },
    { source := ⟨142, by decide⟩, target := ⟨93, by decide⟩, channel := 1 },
    { source := ⟨142, by decide⟩, target := ⟨12, by decide⟩, channel := 1 },
    { source := ⟨142, by decide⟩, target := ⟨174, by decide⟩, channel := 1 },
    { source := ⟨143, by decide⟩, target := ⟨86, by decide⟩, channel := 0 },
    { source := ⟨143, by decide⟩, target := ⟨93, by decide⟩, channel := 1 },
    { source := ⟨143, by decide⟩, target := ⟨12, by decide⟩, channel := 1 },
    { source := ⟨143, by decide⟩, target := ⟨174, by decide⟩, channel := 1 },
    { source := ⟨144, by decide⟩, target := ⟨98, by decide⟩, channel := 0 },
    { source := ⟨144, by decide⟩, target := ⟨193, by decide⟩, channel := 2 },
    { source := ⟨144, by decide⟩, target := ⟨31, by decide⟩, channel := 2 },
    { source := ⟨144, by decide⟩, target := ⟨112, by decide⟩, channel := 2 },
    { source := ⟨145, by decide⟩, target := ⟨98, by decide⟩, channel := 0 },
    { source := ⟨145, by decide⟩, target := ⟨193, by decide⟩, channel := 2 },
    { source := ⟨145, by decide⟩, target := ⟨31, by decide⟩, channel := 2 },
    { source := ⟨145, by decide⟩, target := ⟨112, by decide⟩, channel := 2 },
    { source := ⟨146, by decide⟩, target := ⟨98, by decide⟩, channel := 0 },
    { source := ⟨146, by decide⟩, target := ⟨193, by decide⟩, channel := 2 },
    { source := ⟨146, by decide⟩, target := ⟨31, by decide⟩, channel := 2 },
    { source := ⟨146, by decide⟩, target := ⟨112, by decide⟩, channel := 2 },
    { source := ⟨147, by decide⟩, target := ⟨110, by decide⟩, channel := 0 },
    { source := ⟨148, by decide⟩, target := ⟨110, by decide⟩, channel := 0 },
    { source := ⟨149, by decide⟩, target := ⟨110, by decide⟩, channel := 0 },
    { source := ⟨150, by decide⟩, target := ⟨122, by decide⟩, channel := 0 },
    { source := ⟨150, by decide⟩, target := ⟨99, by decide⟩, channel := 1 },
    { source := ⟨150, by decide⟩, target := ⟨18, by decide⟩, channel := 1 },
    { source := ⟨150, by decide⟩, target := ⟨180, by decide⟩, channel := 1 },
    { source := ⟨151, by decide⟩, target := ⟨122, by decide⟩, channel := 0 },
    { source := ⟨151, by decide⟩, target := ⟨99, by decide⟩, channel := 1 },
    { source := ⟨151, by decide⟩, target := ⟨18, by decide⟩, channel := 1 },
    { source := ⟨151, by decide⟩, target := ⟨180, by decide⟩, channel := 1 },
    { source := ⟨152, by decide⟩, target := ⟨122, by decide⟩, channel := 0 },
    { source := ⟨152, by decide⟩, target := ⟨99, by decide⟩, channel := 1 },
    { source := ⟨152, by decide⟩, target := ⟨18, by decide⟩, channel := 1 },
    { source := ⟨152, by decide⟩, target := ⟨180, by decide⟩, channel := 1 },
    { source := ⟨153, by decide⟩, target := ⟨134, by decide⟩, channel := 0 },
    { source := ⟨153, by decide⟩, target := ⟨205, by decide⟩, channel := 2 },
    { source := ⟨153, by decide⟩, target := ⟨43, by decide⟩, channel := 2 },
    { source := ⟨153, by decide⟩, target := ⟨124, by decide⟩, channel := 2 },
    { source := ⟨154, by decide⟩, target := ⟨134, by decide⟩, channel := 0 },
    { source := ⟨154, by decide⟩, target := ⟨205, by decide⟩, channel := 2 },
    { source := ⟨154, by decide⟩, target := ⟨43, by decide⟩, channel := 2 },
    { source := ⟨154, by decide⟩, target := ⟨124, by decide⟩, channel := 2 },
    { source := ⟨155, by decide⟩, target := ⟨134, by decide⟩, channel := 0 },
    { source := ⟨155, by decide⟩, target := ⟨205, by decide⟩, channel := 2 },
    { source := ⟨155, by decide⟩, target := ⟨43, by decide⟩, channel := 2 },
    { source := ⟨155, by decide⟩, target := ⟨124, by decide⟩, channel := 2 },
    { source := ⟨156, by decide⟩, target := ⟨146, by decide⟩, channel := 0 },
    { source := ⟨157, by decide⟩, target := ⟨146, by decide⟩, channel := 0 },
    { source := ⟨158, by decide⟩, target := ⟨146, by decide⟩, channel := 0 },
    { source := ⟨159, by decide⟩, target := ⟨158, by decide⟩, channel := 0 },
    { source := ⟨159, by decide⟩, target := ⟨105, by decide⟩, channel := 1 },
    { source := ⟨159, by decide⟩, target := ⟨24, by decide⟩, channel := 1 },
    { source := ⟨159, by decide⟩, target := ⟨186, by decide⟩, channel := 1 },
    { source := ⟨160, by decide⟩, target := ⟨158, by decide⟩, channel := 0 },
    { source := ⟨160, by decide⟩, target := ⟨105, by decide⟩, channel := 1 },
    { source := ⟨160, by decide⟩, target := ⟨24, by decide⟩, channel := 1 },
    { source := ⟨160, by decide⟩, target := ⟨186, by decide⟩, channel := 1 },
    { source := ⟨161, by decide⟩, target := ⟨158, by decide⟩, channel := 0 },
    { source := ⟨161, by decide⟩, target := ⟨105, by decide⟩, channel := 1 },
    { source := ⟨161, by decide⟩, target := ⟨24, by decide⟩, channel := 1 },
    { source := ⟨161, by decide⟩, target := ⟨186, by decide⟩, channel := 1 },
    { source := ⟨162, by decide⟩, target := ⟨170, by decide⟩, channel := 0 },
    { source := ⟨162, by decide⟩, target := ⟨217, by decide⟩, channel := 2 },
    { source := ⟨162, by decide⟩, target := ⟨55, by decide⟩, channel := 2 },
    { source := ⟨162, by decide⟩, target := ⟨136, by decide⟩, channel := 2 },
    { source := ⟨163, by decide⟩, target := ⟨170, by decide⟩, channel := 0 },
    { source := ⟨163, by decide⟩, target := ⟨217, by decide⟩, channel := 2 },
    { source := ⟨163, by decide⟩, target := ⟨55, by decide⟩, channel := 2 },
    { source := ⟨163, by decide⟩, target := ⟨136, by decide⟩, channel := 2 },
    { source := ⟨164, by decide⟩, target := ⟨170, by decide⟩, channel := 0 },
    { source := ⟨164, by decide⟩, target := ⟨217, by decide⟩, channel := 2 },
    { source := ⟨164, by decide⟩, target := ⟨55, by decide⟩, channel := 2 },
    { source := ⟨164, by decide⟩, target := ⟨136, by decide⟩, channel := 2 },
    { source := ⟨165, by decide⟩, target := ⟨182, by decide⟩, channel := 0 },
    { source := ⟨166, by decide⟩, target := ⟨182, by decide⟩, channel := 0 },
    { source := ⟨167, by decide⟩, target := ⟨182, by decide⟩, channel := 0 },
    { source := ⟨168, by decide⟩, target := ⟨194, by decide⟩, channel := 0 },
    { source := ⟨168, by decide⟩, target := ⟨111, by decide⟩, channel := 1 },
    { source := ⟨168, by decide⟩, target := ⟨30, by decide⟩, channel := 1 },
    { source := ⟨168, by decide⟩, target := ⟨192, by decide⟩, channel := 1 },
    { source := ⟨169, by decide⟩, target := ⟨194, by decide⟩, channel := 0 },
    { source := ⟨169, by decide⟩, target := ⟨111, by decide⟩, channel := 1 },
    { source := ⟨169, by decide⟩, target := ⟨30, by decide⟩, channel := 1 },
    { source := ⟨169, by decide⟩, target := ⟨192, by decide⟩, channel := 1 },
    { source := ⟨170, by decide⟩, target := ⟨194, by decide⟩, channel := 0 },
    { source := ⟨170, by decide⟩, target := ⟨111, by decide⟩, channel := 1 },
    { source := ⟨170, by decide⟩, target := ⟨30, by decide⟩, channel := 1 },
    { source := ⟨170, by decide⟩, target := ⟨192, by decide⟩, channel := 1 },
    { source := ⟨171, by decide⟩, target := ⟨206, by decide⟩, channel := 0 },
    { source := ⟨171, by decide⟩, target := ⟨229, by decide⟩, channel := 2 },
    { source := ⟨171, by decide⟩, target := ⟨67, by decide⟩, channel := 2 },
    { source := ⟨171, by decide⟩, target := ⟨148, by decide⟩, channel := 2 },
    { source := ⟨172, by decide⟩, target := ⟨206, by decide⟩, channel := 0 },
    { source := ⟨172, by decide⟩, target := ⟨229, by decide⟩, channel := 2 },
    { source := ⟨172, by decide⟩, target := ⟨67, by decide⟩, channel := 2 },
    { source := ⟨172, by decide⟩, target := ⟨148, by decide⟩, channel := 2 },
    { source := ⟨173, by decide⟩, target := ⟨206, by decide⟩, channel := 0 },
    { source := ⟨173, by decide⟩, target := ⟨229, by decide⟩, channel := 2 },
    { source := ⟨173, by decide⟩, target := ⟨67, by decide⟩, channel := 2 },
    { source := ⟨173, by decide⟩, target := ⟨148, by decide⟩, channel := 2 },
    { source := ⟨174, by decide⟩, target := ⟨218, by decide⟩, channel := 0 },
    { source := ⟨175, by decide⟩, target := ⟨218, by decide⟩, channel := 0 },
    { source := ⟨176, by decide⟩, target := ⟨218, by decide⟩, channel := 0 },
    { source := ⟨177, by decide⟩, target := ⟨230, by decide⟩, channel := 0 },
    { source := ⟨177, by decide⟩, target := ⟨117, by decide⟩, channel := 1 },
    { source := ⟨177, by decide⟩, target := ⟨36, by decide⟩, channel := 1 },
    { source := ⟨177, by decide⟩, target := ⟨198, by decide⟩, channel := 1 },
    { source := ⟨178, by decide⟩, target := ⟨230, by decide⟩, channel := 0 },
    { source := ⟨178, by decide⟩, target := ⟨117, by decide⟩, channel := 1 },
    { source := ⟨178, by decide⟩, target := ⟨36, by decide⟩, channel := 1 },
    { source := ⟨178, by decide⟩, target := ⟨198, by decide⟩, channel := 1 },
    { source := ⟨179, by decide⟩, target := ⟨230, by decide⟩, channel := 0 },
    { source := ⟨179, by decide⟩, target := ⟨117, by decide⟩, channel := 1 },
    { source := ⟨179, by decide⟩, target := ⟨36, by decide⟩, channel := 1 },
    { source := ⟨179, by decide⟩, target := ⟨198, by decide⟩, channel := 1 },
    { source := ⟨180, by decide⟩, target := ⟨242, by decide⟩, channel := 0 },
    { source := ⟨180, by decide⟩, target := ⟨241, by decide⟩, channel := 2 },
    { source := ⟨180, by decide⟩, target := ⟨79, by decide⟩, channel := 2 },
    { source := ⟨180, by decide⟩, target := ⟨160, by decide⟩, channel := 2 },
    { source := ⟨181, by decide⟩, target := ⟨242, by decide⟩, channel := 0 },
    { source := ⟨181, by decide⟩, target := ⟨241, by decide⟩, channel := 2 },
    { source := ⟨181, by decide⟩, target := ⟨79, by decide⟩, channel := 2 },
    { source := ⟨181, by decide⟩, target := ⟨160, by decide⟩, channel := 2 },
    { source := ⟨182, by decide⟩, target := ⟨242, by decide⟩, channel := 0 },
    { source := ⟨182, by decide⟩, target := ⟨241, by decide⟩, channel := 2 },
    { source := ⟨182, by decide⟩, target := ⟨79, by decide⟩, channel := 2 },
    { source := ⟨182, by decide⟩, target := ⟨160, by decide⟩, channel := 2 },
    { source := ⟨183, by decide⟩, target := ⟨11, by decide⟩, channel := 0 },
    { source := ⟨184, by decide⟩, target := ⟨11, by decide⟩, channel := 0 },
    { source := ⟨185, by decide⟩, target := ⟨11, by decide⟩, channel := 0 },
    { source := ⟨186, by decide⟩, target := ⟨23, by decide⟩, channel := 0 },
    { source := ⟨186, by decide⟩, target := ⟨123, by decide⟩, channel := 1 },
    { source := ⟨186, by decide⟩, target := ⟨42, by decide⟩, channel := 1 },
    { source := ⟨186, by decide⟩, target := ⟨204, by decide⟩, channel := 1 },
    { source := ⟨187, by decide⟩, target := ⟨23, by decide⟩, channel := 0 },
    { source := ⟨187, by decide⟩, target := ⟨123, by decide⟩, channel := 1 },
    { source := ⟨187, by decide⟩, target := ⟨42, by decide⟩, channel := 1 },
    { source := ⟨187, by decide⟩, target := ⟨204, by decide⟩, channel := 1 },
    { source := ⟨188, by decide⟩, target := ⟨23, by decide⟩, channel := 0 },
    { source := ⟨188, by decide⟩, target := ⟨123, by decide⟩, channel := 1 },
    { source := ⟨188, by decide⟩, target := ⟨42, by decide⟩, channel := 1 },
    { source := ⟨188, by decide⟩, target := ⟨204, by decide⟩, channel := 1 },
    { source := ⟨189, by decide⟩, target := ⟨35, by decide⟩, channel := 0 },
    { source := ⟨189, by decide⟩, target := ⟨10, by decide⟩, channel := 2 },
    { source := ⟨189, by decide⟩, target := ⟨91, by decide⟩, channel := 2 },
    { source := ⟨189, by decide⟩, target := ⟨172, by decide⟩, channel := 2 },
    { source := ⟨190, by decide⟩, target := ⟨35, by decide⟩, channel := 0 },
    { source := ⟨190, by decide⟩, target := ⟨10, by decide⟩, channel := 2 },
    { source := ⟨190, by decide⟩, target := ⟨91, by decide⟩, channel := 2 },
    { source := ⟨190, by decide⟩, target := ⟨172, by decide⟩, channel := 2 },
    { source := ⟨191, by decide⟩, target := ⟨35, by decide⟩, channel := 0 },
    { source := ⟨191, by decide⟩, target := ⟨10, by decide⟩, channel := 2 },
    { source := ⟨191, by decide⟩, target := ⟨91, by decide⟩, channel := 2 },
    { source := ⟨191, by decide⟩, target := ⟨172, by decide⟩, channel := 2 },
    { source := ⟨192, by decide⟩, target := ⟨47, by decide⟩, channel := 0 },
    { source := ⟨193, by decide⟩, target := ⟨47, by decide⟩, channel := 0 },
    { source := ⟨194, by decide⟩, target := ⟨47, by decide⟩, channel := 0 },
    { source := ⟨195, by decide⟩, target := ⟨59, by decide⟩, channel := 0 },
    { source := ⟨195, by decide⟩, target := ⟨129, by decide⟩, channel := 1 },
    { source := ⟨195, by decide⟩, target := ⟨48, by decide⟩, channel := 1 },
    { source := ⟨195, by decide⟩, target := ⟨210, by decide⟩, channel := 1 },
    { source := ⟨196, by decide⟩, target := ⟨59, by decide⟩, channel := 0 },
    { source := ⟨196, by decide⟩, target := ⟨129, by decide⟩, channel := 1 },
    { source := ⟨196, by decide⟩, target := ⟨48, by decide⟩, channel := 1 },
    { source := ⟨196, by decide⟩, target := ⟨210, by decide⟩, channel := 1 },
    { source := ⟨197, by decide⟩, target := ⟨59, by decide⟩, channel := 0 },
    { source := ⟨197, by decide⟩, target := ⟨129, by decide⟩, channel := 1 },
    { source := ⟨197, by decide⟩, target := ⟨48, by decide⟩, channel := 1 },
    { source := ⟨197, by decide⟩, target := ⟨210, by decide⟩, channel := 1 },
    { source := ⟨198, by decide⟩, target := ⟨71, by decide⟩, channel := 0 },
    { source := ⟨198, by decide⟩, target := ⟨22, by decide⟩, channel := 2 },
    { source := ⟨198, by decide⟩, target := ⟨103, by decide⟩, channel := 2 },
    { source := ⟨198, by decide⟩, target := ⟨184, by decide⟩, channel := 2 },
    { source := ⟨199, by decide⟩, target := ⟨71, by decide⟩, channel := 0 },
    { source := ⟨199, by decide⟩, target := ⟨22, by decide⟩, channel := 2 },
    { source := ⟨199, by decide⟩, target := ⟨103, by decide⟩, channel := 2 },
    { source := ⟨199, by decide⟩, target := ⟨184, by decide⟩, channel := 2 },
    { source := ⟨200, by decide⟩, target := ⟨71, by decide⟩, channel := 0 },
    { source := ⟨200, by decide⟩, target := ⟨22, by decide⟩, channel := 2 },
    { source := ⟨200, by decide⟩, target := ⟨103, by decide⟩, channel := 2 },
    { source := ⟨200, by decide⟩, target := ⟨184, by decide⟩, channel := 2 },
    { source := ⟨201, by decide⟩, target := ⟨83, by decide⟩, channel := 0 },
    { source := ⟨202, by decide⟩, target := ⟨83, by decide⟩, channel := 0 },
    { source := ⟨203, by decide⟩, target := ⟨83, by decide⟩, channel := 0 },
    { source := ⟨204, by decide⟩, target := ⟨95, by decide⟩, channel := 0 },
    { source := ⟨204, by decide⟩, target := ⟨135, by decide⟩, channel := 1 },
    { source := ⟨204, by decide⟩, target := ⟨54, by decide⟩, channel := 1 },
    { source := ⟨204, by decide⟩, target := ⟨216, by decide⟩, channel := 1 },
    { source := ⟨205, by decide⟩, target := ⟨95, by decide⟩, channel := 0 },
    { source := ⟨205, by decide⟩, target := ⟨135, by decide⟩, channel := 1 },
    { source := ⟨205, by decide⟩, target := ⟨54, by decide⟩, channel := 1 },
    { source := ⟨205, by decide⟩, target := ⟨216, by decide⟩, channel := 1 },
    { source := ⟨206, by decide⟩, target := ⟨95, by decide⟩, channel := 0 },
    { source := ⟨206, by decide⟩, target := ⟨135, by decide⟩, channel := 1 },
    { source := ⟨206, by decide⟩, target := ⟨54, by decide⟩, channel := 1 },
    { source := ⟨206, by decide⟩, target := ⟨216, by decide⟩, channel := 1 },
    { source := ⟨207, by decide⟩, target := ⟨107, by decide⟩, channel := 0 },
    { source := ⟨207, by decide⟩, target := ⟨34, by decide⟩, channel := 2 },
    { source := ⟨207, by decide⟩, target := ⟨115, by decide⟩, channel := 2 },
    { source := ⟨207, by decide⟩, target := ⟨196, by decide⟩, channel := 2 },
    { source := ⟨208, by decide⟩, target := ⟨107, by decide⟩, channel := 0 },
    { source := ⟨208, by decide⟩, target := ⟨34, by decide⟩, channel := 2 },
    { source := ⟨208, by decide⟩, target := ⟨115, by decide⟩, channel := 2 },
    { source := ⟨208, by decide⟩, target := ⟨196, by decide⟩, channel := 2 },
    { source := ⟨209, by decide⟩, target := ⟨107, by decide⟩, channel := 0 },
    { source := ⟨209, by decide⟩, target := ⟨34, by decide⟩, channel := 2 },
    { source := ⟨209, by decide⟩, target := ⟨115, by decide⟩, channel := 2 },
    { source := ⟨209, by decide⟩, target := ⟨196, by decide⟩, channel := 2 },
    { source := ⟨210, by decide⟩, target := ⟨119, by decide⟩, channel := 0 },
    { source := ⟨211, by decide⟩, target := ⟨119, by decide⟩, channel := 0 },
    { source := ⟨212, by decide⟩, target := ⟨119, by decide⟩, channel := 0 },
    { source := ⟨213, by decide⟩, target := ⟨131, by decide⟩, channel := 0 },
    { source := ⟨213, by decide⟩, target := ⟨141, by decide⟩, channel := 1 },
    { source := ⟨213, by decide⟩, target := ⟨60, by decide⟩, channel := 1 },
    { source := ⟨213, by decide⟩, target := ⟨222, by decide⟩, channel := 1 },
    { source := ⟨214, by decide⟩, target := ⟨131, by decide⟩, channel := 0 },
    { source := ⟨214, by decide⟩, target := ⟨141, by decide⟩, channel := 1 },
    { source := ⟨214, by decide⟩, target := ⟨60, by decide⟩, channel := 1 },
    { source := ⟨214, by decide⟩, target := ⟨222, by decide⟩, channel := 1 },
    { source := ⟨215, by decide⟩, target := ⟨131, by decide⟩, channel := 0 },
    { source := ⟨215, by decide⟩, target := ⟨141, by decide⟩, channel := 1 },
    { source := ⟨215, by decide⟩, target := ⟨60, by decide⟩, channel := 1 },
    { source := ⟨215, by decide⟩, target := ⟨222, by decide⟩, channel := 1 },
    { source := ⟨216, by decide⟩, target := ⟨143, by decide⟩, channel := 0 },
    { source := ⟨216, by decide⟩, target := ⟨46, by decide⟩, channel := 2 },
    { source := ⟨216, by decide⟩, target := ⟨127, by decide⟩, channel := 2 },
    { source := ⟨216, by decide⟩, target := ⟨208, by decide⟩, channel := 2 },
    { source := ⟨217, by decide⟩, target := ⟨143, by decide⟩, channel := 0 },
    { source := ⟨217, by decide⟩, target := ⟨46, by decide⟩, channel := 2 },
    { source := ⟨217, by decide⟩, target := ⟨127, by decide⟩, channel := 2 },
    { source := ⟨217, by decide⟩, target := ⟨208, by decide⟩, channel := 2 },
    { source := ⟨218, by decide⟩, target := ⟨143, by decide⟩, channel := 0 },
    { source := ⟨218, by decide⟩, target := ⟨46, by decide⟩, channel := 2 },
    { source := ⟨218, by decide⟩, target := ⟨127, by decide⟩, channel := 2 },
    { source := ⟨218, by decide⟩, target := ⟨208, by decide⟩, channel := 2 },
    { source := ⟨219, by decide⟩, target := ⟨155, by decide⟩, channel := 0 },
    { source := ⟨220, by decide⟩, target := ⟨155, by decide⟩, channel := 0 },
    { source := ⟨221, by decide⟩, target := ⟨155, by decide⟩, channel := 0 },
    { source := ⟨222, by decide⟩, target := ⟨167, by decide⟩, channel := 0 },
    { source := ⟨222, by decide⟩, target := ⟨147, by decide⟩, channel := 1 },
    { source := ⟨222, by decide⟩, target := ⟨66, by decide⟩, channel := 1 },
    { source := ⟨222, by decide⟩, target := ⟨228, by decide⟩, channel := 1 },
    { source := ⟨223, by decide⟩, target := ⟨167, by decide⟩, channel := 0 },
    { source := ⟨223, by decide⟩, target := ⟨147, by decide⟩, channel := 1 },
    { source := ⟨223, by decide⟩, target := ⟨66, by decide⟩, channel := 1 },
    { source := ⟨223, by decide⟩, target := ⟨228, by decide⟩, channel := 1 },
    { source := ⟨224, by decide⟩, target := ⟨167, by decide⟩, channel := 0 },
    { source := ⟨224, by decide⟩, target := ⟨147, by decide⟩, channel := 1 },
    { source := ⟨224, by decide⟩, target := ⟨66, by decide⟩, channel := 1 },
    { source := ⟨224, by decide⟩, target := ⟨228, by decide⟩, channel := 1 },
    { source := ⟨225, by decide⟩, target := ⟨179, by decide⟩, channel := 0 },
    { source := ⟨225, by decide⟩, target := ⟨58, by decide⟩, channel := 2 },
    { source := ⟨225, by decide⟩, target := ⟨139, by decide⟩, channel := 2 },
    { source := ⟨225, by decide⟩, target := ⟨220, by decide⟩, channel := 2 },
    { source := ⟨226, by decide⟩, target := ⟨179, by decide⟩, channel := 0 },
    { source := ⟨226, by decide⟩, target := ⟨58, by decide⟩, channel := 2 },
    { source := ⟨226, by decide⟩, target := ⟨139, by decide⟩, channel := 2 },
    { source := ⟨226, by decide⟩, target := ⟨220, by decide⟩, channel := 2 },
    { source := ⟨227, by decide⟩, target := ⟨179, by decide⟩, channel := 0 },
    { source := ⟨227, by decide⟩, target := ⟨58, by decide⟩, channel := 2 },
    { source := ⟨227, by decide⟩, target := ⟨139, by decide⟩, channel := 2 },
    { source := ⟨227, by decide⟩, target := ⟨220, by decide⟩, channel := 2 },
    { source := ⟨228, by decide⟩, target := ⟨191, by decide⟩, channel := 0 },
    { source := ⟨229, by decide⟩, target := ⟨191, by decide⟩, channel := 0 },
    { source := ⟨230, by decide⟩, target := ⟨191, by decide⟩, channel := 0 },
    { source := ⟨231, by decide⟩, target := ⟨203, by decide⟩, channel := 0 },
    { source := ⟨231, by decide⟩, target := ⟨153, by decide⟩, channel := 1 },
    { source := ⟨231, by decide⟩, target := ⟨72, by decide⟩, channel := 1 },
    { source := ⟨231, by decide⟩, target := ⟨234, by decide⟩, channel := 1 },
    { source := ⟨232, by decide⟩, target := ⟨203, by decide⟩, channel := 0 },
    { source := ⟨232, by decide⟩, target := ⟨153, by decide⟩, channel := 1 },
    { source := ⟨232, by decide⟩, target := ⟨72, by decide⟩, channel := 1 },
    { source := ⟨232, by decide⟩, target := ⟨234, by decide⟩, channel := 1 },
    { source := ⟨233, by decide⟩, target := ⟨203, by decide⟩, channel := 0 },
    { source := ⟨233, by decide⟩, target := ⟨153, by decide⟩, channel := 1 },
    { source := ⟨233, by decide⟩, target := ⟨72, by decide⟩, channel := 1 },
    { source := ⟨233, by decide⟩, target := ⟨234, by decide⟩, channel := 1 },
    { source := ⟨234, by decide⟩, target := ⟨215, by decide⟩, channel := 0 },
    { source := ⟨234, by decide⟩, target := ⟨70, by decide⟩, channel := 2 },
    { source := ⟨234, by decide⟩, target := ⟨151, by decide⟩, channel := 2 },
    { source := ⟨234, by decide⟩, target := ⟨232, by decide⟩, channel := 2 },
    { source := ⟨235, by decide⟩, target := ⟨215, by decide⟩, channel := 0 },
    { source := ⟨235, by decide⟩, target := ⟨70, by decide⟩, channel := 2 },
    { source := ⟨235, by decide⟩, target := ⟨151, by decide⟩, channel := 2 },
    { source := ⟨235, by decide⟩, target := ⟨232, by decide⟩, channel := 2 },
    { source := ⟨236, by decide⟩, target := ⟨215, by decide⟩, channel := 0 },
    { source := ⟨236, by decide⟩, target := ⟨70, by decide⟩, channel := 2 },
    { source := ⟨236, by decide⟩, target := ⟨151, by decide⟩, channel := 2 },
    { source := ⟨236, by decide⟩, target := ⟨232, by decide⟩, channel := 2 },
    { source := ⟨237, by decide⟩, target := ⟨227, by decide⟩, channel := 0 },
    { source := ⟨238, by decide⟩, target := ⟨227, by decide⟩, channel := 0 },
    { source := ⟨239, by decide⟩, target := ⟨227, by decide⟩, channel := 0 },
    { source := ⟨240, by decide⟩, target := ⟨239, by decide⟩, channel := 0 },
    { source := ⟨240, by decide⟩, target := ⟨159, by decide⟩, channel := 1 },
    { source := ⟨240, by decide⟩, target := ⟨78, by decide⟩, channel := 1 },
    { source := ⟨240, by decide⟩, target := ⟨240, by decide⟩, channel := 1 },
    { source := ⟨241, by decide⟩, target := ⟨239, by decide⟩, channel := 0 },
    { source := ⟨241, by decide⟩, target := ⟨159, by decide⟩, channel := 1 },
    { source := ⟨241, by decide⟩, target := ⟨78, by decide⟩, channel := 1 },
    { source := ⟨241, by decide⟩, target := ⟨240, by decide⟩, channel := 1 },
    { source := ⟨242, by decide⟩, target := ⟨239, by decide⟩, channel := 0 },
    { source := ⟨242, by decide⟩, target := ⟨159, by decide⟩, channel := 1 },
    { source := ⟨242, by decide⟩, target := ⟨78, by decide⟩, channel := 1 },
    { source := ⟨242, by decide⟩, target := ⟨240, by decide⟩, channel := 1 }
  ]

def integerWeights : Vector Nat 243 :=
  ⟨#[
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664,
    5581,
    3100,
    3664
  ], by decide⟩

def rhoStar : ℝ := 9 / 5

def alpha : ℝ := Real.log 3 / Real.log 2

def channelWeight : Nat → ℝ
  | 0 => Real.rpow rhoStar (-2)
  | 1 => Real.rpow rhoStar (alpha - 1) / 3
  | 2 => Real.rpow rhoStar (alpha - 2) / 3
  | _ => 0

def coreMatrix (s t : Fin 243) : ℝ :=
  (coreEdges.filter (fun e => e.source = s ∧ e.target = t)).foldr
    (fun e acc => channelWeight e.channel + acc) 0

def frozenWeight (s : Fin 243) : ℝ :=
  (integerWeights.get s : ℝ) / 1000000

theorem core_edge_count : coreEdges.length = 729 := by
  native_decide

theorem frozen_weight_count : integerWeights.toList.length = 243 := by
  native_decide

theorem core_edges_have_valid_channels :
    coreEdges.all (fun e => e.channel < 3) = true := by
  native_decide

theorem channelWeight_nonneg (c : Nat) : 0 ≤ channelWeight c := by
  cases c with
  | zero =>
      dsimp [channelWeight]
      exact Real.rpow_nonneg (by norm_num [rhoStar]) _
  | succ c =>
      cases c with
      | zero =>
          dsimp [channelWeight]
          exact div_nonneg (Real.rpow_nonneg (by norm_num [rhoStar]) _) (by norm_num)
      | succ c =>
          cases c with
          | zero =>
              dsimp [channelWeight]
              exact div_nonneg (Real.rpow_nonneg (by norm_num [rhoStar]) _) (by norm_num)
          | succ c => simp [channelWeight]

theorem coreMatrix_nonneg (s t : Fin 243) : 0 ≤ coreMatrix s t := by
  have list_nonneg : ∀ xs : List CoreEdge,
      0 ≤ xs.foldr (fun e acc => channelWeight e.channel + acc) 0 := by
    intro xs
    induction xs with
    | nil => simp
    | cons e es ih =>
        simp only [List.foldr]
        exact add_nonneg (channelWeight_nonneg e.channel) ih
  simpa [coreMatrix] using
    list_nonneg (coreEdges.filter (fun e => e.source = s ∧ e.target = t))

theorem frozenWeight_nonneg (s : Fin 243) : 0 ≤ frozenWeight s := by
  unfold frozenWeight
  exact div_nonneg (by positivity) (by norm_num)

def rowCertificate : Prop :=
  ∀ s : Fin 243, (101 / 100 : ℝ) * frozenWeight s ≤
    ∑ t : Fin 243, coreMatrix s t * frozenWeight t

theorem rowCertificate_is_explicit_obligation :
    rowCertificate ↔
      ∀ s : Fin 243, (101 / 100 : ℝ) * frozenWeight s ≤
        ∑ t : Fin 243, coreMatrix s t * frozenWeight t := by
  rfl

end F3ExactCoreMatrix
end KL2003
end CollatzClassical
