import CollatzClassical.KL2003.KL2003GeneralKProvenancedSchedulerDepth

open CollatzClassical KL2003

#print axioms KL2003.GeneralKProvenancedSchedulerDepth.four_mul_terminalFuel_child_lt
#print axioms KL2003.GeneralKProvenancedSchedulerDepth.treeFuel_d1ReducedSourceSplit_lt
#print axioms KL2003.GeneralKProvenancedSchedulerDepth.treeFuel_d3ReducedSourceSplit_lt
#print axioms KL2003.GeneralKProvenancedSchedulerDepth.treeFuel_sourceSplit_lt_of_mod_five
#print axioms KL2003.GeneralKProvenancedSchedulerDepth.treeFuel_provenancedReplaceAt_lt
#print axioms KL2003.GeneralKProvenancedSchedulerDepth.treeFuel_sourceStep_lt
#print axioms KL2003.GeneralKProvenancedSchedulerDepth.descendingFuel_add_index_le
#print axioms KL2003.GeneralKProvenancedSchedulerDepth.exists_selectedOccurrence_walk_length_gt
