import CollatzClassical.KL2003.KL2003M0CRetardedInduction

namespace CollatzClassical
namespace KL2003

#print axioms k2_retarded_inputs_from_closed_certificate
#print axioms baseSegment_phi22
#print axioms baseSegment_phi25
#print axioms baseSegment_phi28
#print axioms weightedBaseSegment_phi22
#print axioms weightedBaseSegment_phi25
#print axioms weightedBaseSegment_phi28
#print axioms DeltaV2_pos
#print axioms c22R_pos
#print axioms c25R_pos
#print axioms c28R_pos
#print axioms c22R_le_two
#print axioms c25R_le_two
#print axioms c28R_le_two
#print axioms lambdaR_rpow_le_pow_fourteen
#print axioms DeltaV2_mul_two_mul_lambdaR_pow_fourteen
#print axioms DeltaV2_mul_coeff_mul_lambdaR_rpow_le_one
#print axioms DeltaV2_mul_c22R_mul_lambdaR_rpow_le_one
#print axioms DeltaV2_mul_c25R_mul_lambdaR_rpow_le_one
#print axioms DeltaV2_mul_c28R_mul_lambdaR_rpow_le_one
#print axioms base_weighted_of_unit
#print axioms epsilon0_pos
#print axioms epsilon0_nonneg
#print axioms epsilon0_lt_one
#print axioms lambdaR_cube_lt_four
#print axioms pad_inv_power_ge_four
#print axioms lambdaR_three_epsilon_le_pad_inv
#print axioms lambda_neg_three_epsilon_ge
#print axioms padded_row22_slack_eq
#print axioms padded_row22_arithmetic
#print axioms row25_no_advanced_pad_arithmetic
#print axioms padded_row28_slack_eq
#print axioms padded_row28_arithmetic
#print axioms deltaM0C_pos
#print axioms one_fifth_lt_deltaM0C
#print axioms deltaM0C_le_two
#print axioms alpha_pos
#print axioms alpha_nonneg
#print axioms one_le_alpha
#print axioms three_halves_le_alpha
#print axioms shift_minus_two_le_neg_deltaM0C
#print axioms shift_alpha_minus_two_le_neg_deltaM0C
#print axioms shift_alpha_minus_three_le_neg_deltaM0C
#print axioms shift_two_alpha_minus_five_le_neg_deltaM0C
#print axioms shift_three_alpha_minus_five_eq_neg_deltaM0C
#print axioms shift_alpha_minus2_pad_le_shift_alpha_minus_two
#print axioms shift_alpha_minus3_pad_le_shift_alpha_minus_three
#print axioms shift2_alpha_minus5_pad2_le_shift_two_alpha_minus_five
#print axioms shift3_alpha_minus5_pad3_le_shift_three_alpha_minus_five
#print axioms shift_alpha_minus2_pad_le_neg_deltaM0C
#print axioms shift_alpha_minus3_pad_le_neg_deltaM0C
#print axioms shift2_alpha_minus5_pad2_le_neg_deltaM0C
#print axioms shift3_alpha_minus5_pad3_le_neg_deltaM0C
#print axioms retardedRank_drop
#print axioms retardedRank_drop_minus_two
#print axioms retardedRank_drop_alpha_minus_two
#print axioms retardedRank_drop_alpha_minus_three
#print axioms retardedRank_drop_two_alpha_minus_five
#print axioms retardedRank_drop_three_alpha_minus_five
#print axioms retardedRank_drop_shiftAlphaMinus2Pad
#print axioms retardedRank_drop_shiftAlphaMinus3Pad
#print axioms retardedRank_drop_shift2AlphaMinus5Pad2
#print axioms retardedRank_drop_shift3AlphaMinus5Pad3

end KL2003
end CollatzClassical
