import CollatzClassical.KL2003.KL2003GeneralKCriticalAdvancedDominance

open CollatzClassical KL2003

#print axioms KL2003.GeneralKCriticalAdvancedDominance.raw_target_shift_le_ancestor_shift_of_noDeletionWitness
#print axioms KL2003.GeneralKCriticalAdvancedDominance.dominatesSameModePrefixes_of_noDeletionWitness
#print axioms KL2003.GeneralKCriticalAdvancedDominance.AllLabelsAdvancedDominance.criticalSourceStep
#print axioms KL2003.GeneralKCriticalAdvancedDominance.run_allLabelsAdvancedDominance
#print axioms KL2003.GeneralKCriticalAdvancedDominance.allSelectedPrefixesAdvancedDominance
#print axioms KL2003.GeneralKCriticalAdvancedDominance.extractedCriticalBranch_advancedArrivalsNonincreasing
