import CollatzClassical.KL2003.KL2003GeneralKUniformRetardedWindow

#print axioms CollatzClassical.KL2003.GeneralKUniformRetardedWindow.run_allTerminalWalkLengthLe
#print axioms CollatzClassical.KL2003.GeneralKUniformRetardedWindow.normalExpr_allLeaves_boundedProvenance
#print axioms CollatzClassical.KL2003.GeneralKUniformRetardedWindow.uniformMu_pos
#print axioms CollatzClassical.KL2003.GeneralKUniformRetardedWindow.uniformMu_le_uniformNu
#print axioms CollatzClassical.KL2003.GeneralKUniformRetardedWindow.sourceELRetardedWitness_selectedExpr_shiftsWithin
#print axioms CollatzClassical.KL2003.GeneralKUniformRetardedWindow.exists_uniform_sourceELRetardedWindow
