import CollatzClassical.KL2003.KL2003GeneralKCriticalTripleWitnessExclusion

open CollatzClassical KL2003

#print axioms KL2003.GeneralKCriticalTripleWitnessExclusion.not_allThreeHaveWitness_of_targetCritical
#print axioms KL2003.GeneralKCriticalTripleWitnessExclusion.witnessRetention_retainedBranchesWitnessFree_of_targetCritical
#print axioms KL2003.GeneralKCriticalTripleWitnessExclusion.criticalWitnessRetention_retainedBranchesWitnessFree_of_targetCritical
