import CollatzClassical.KL2003.KL2003GeneralKProvenancedScheduler

open CollatzClassical KL2003

#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.advancedConfiguration_reduceAt_transport
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.d1Configuration_reduceAt_eq
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.d3Configuration_reduceAt_eq
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.forget_d1ReducedSourceSplit
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.forget_d3ReducedSourceSplit
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.rawReplaceAt_sourceSplit
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.reduceAt_descendSplitMin3_eq_rawReplaceAt
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.forget_provenancedReplaceAt
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.ExpandableOccurrence.sourceStep_forget
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.findExpandableOccurrence_forget
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.sourceScheduledStep_forget
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.run_forget
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.exists_selectedOccurrence
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.findExpandableOccurrence_run_eq_selectedOccurrence
#print axioms KL2003.GeneralKProvenancedScheduler.ProvenancedTree.run_succ_eq_selectedOccurrence_sourceStep
