import CollatzClassical.KL2003.KL2003GeneralKUniformCriticalDepth

open CollatzClassical KL2003

#print axioms KL2003.GeneralKUniformCriticalDepth.run_allLabelsAdvancedDominance_finite
#print axioms KL2003.GeneralKUniformCriticalDepth.uniformSelectedCode_nonnegative
#print axioms KL2003.GeneralKUniformCriticalDepth.uniformSelectedCode_advancedDominance
#print axioms KL2003.GeneralKUniformCriticalDepth.exists_coherent_uniformSelectedCodes_of_unbounded
#print axioms KL2003.GeneralKUniformCriticalDepth.unboundedInfiniteSourceWalk_shiftsNonnegative
#print axioms KL2003.GeneralKUniformCriticalDepth.unboundedInfiniteSourceWalk_advancedArrivalsNonincreasing
#print axioms KL2003.GeneralKUniformCriticalDepth.not_criticalSelectedDepthUnbounded
#print axioms KL2003.GeneralKUniformCriticalDepth.exists_uniform_criticalSelectedDepthBound
