import CollatzClassical.KL2003.KL2003GeneralKDynamicRetardedLowerBound

#print axioms CollatzClassical.KL2003.dynamic_retarded_lower_bound
#print axioms CollatzClassical.KL2003.dynamic_retarded_lower_bound_of_static
#print axioms CollatzClassical.KL2003.GeneralKDynamicRetardedLowerBound.sourceDynamicRow_shiftsWithin
#print axioms CollatzClassical.KL2003.GeneralKDynamicRetardedLowerBound.sourceDynamicRow_evalAt_le
#print axioms CollatzClassical.KL2003.GeneralKDynamicRetardedLowerBound.sourceDynamicRow_coefficient_feasible
#print axioms CollatzClassical.KL2003.GeneralKDynamicRetardedLowerBound.sourceDynamicBase
#print axioms CollatzClassical.KL2003.GeneralKDynamicRetardedLowerBound.sourcePhiK_retarded_lower_bound_for_depthBound
#print axioms CollatzClassical.KL2003.GeneralKDynamicRetardedLowerBound.exists_sourcePhiK_retarded_lower_bound
