import CollatzClassical.KL2003.KL2003GeneralKInfiniteBranchDescent

open CollatzClassical KL2003

#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.castSourceWalk_length
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.castSourceWalk_weight
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.castSourceWalk_contextAdmissible_iff
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.segment_length
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.segment_weight_eval
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.segmentWeightEval_add
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.beta_add
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.recurrentDropAtLength_of_allSegmentsContextAdmissible
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.hasUniformRecurrentDrop_of_allSegmentsContextAdmissible
#print axioms KL2003.GeneralKInfiniteBranchDescent.InfiniteSourceWalk.not_shiftsNonnegative_of_allSegmentsContextAdmissible
