import CollatzClassical.KL2003.KL2003GeneralKEliminationContext

namespace CollatzClassical
namespace KL2003

#print axioms ELTree.Context.plug_normalExpr_eval_mono
#print axioms ELTree.Context.plug_normalExpr_eval_eq
#print axioms ELTree.Context.holeCritical_congr
#print axioms ELTree.Context.plug_normalExpr_eval_eq_of_not_holeCritical
#print axioms ELTree.Context.criticalNodeBounds_of_nodeBounds
#print axioms ELTree.Context.criticalNodeBounds_congr
#print axioms ELTree.Context.criticalAssignment_bound
#print axioms ELTree.sourceSplitTree_criticalNodeBounds
#print axioms ELTree.Context.lift_criticalPath
#print axioms ELTree.Context.terminal_not_holeCritical_of_excludesCriticalLeaf
#print axioms ELTree.Min3Path.reduceAt_normalExpr_eval_eq_of_totallyNoncritical
#print axioms ELTree.Min3Path.reduceAt_normalExpr_eval_eq_of_deletedBranchesTotallyNoncritical
#print axioms ELTree.TerminalPath.deletionWitness_implies_not_holeCritical
#print axioms ELTree.TerminalPath.sourceD1AdvancedConfiguration
#print axioms ELTree.TerminalPath.sourceD3AdvancedConfiguration
#print axioms ELTree.TerminalPath.AdvancedMinConfiguration.descendSplit
#print axioms ELTree.TerminalPath.AdvancedMinConfiguration.reduceAt_normalExpr_eval_eq_of_witnesses
#print axioms ELTree.TerminalPath.AdvancedMinConfiguration.witnessRetention_deletedBranchesHaveWitness
#print axioms ELTree.TerminalPath.AdvancedMinConfiguration.witnessRetention_retainedCount
#print axioms ELTree.TerminalPath.AdvancedMinConfiguration.witnessRetention_reduceAt_normalExpr_eval_eq

end KL2003
end CollatzClassical
