import CollatzClassical.KL2003.KL2003GeneralKAdvancedArrivalBoundedness

open CollatzClassical KL2003

#print axioms KL2003.GeneralKAdvancedArrivalBoundedness.advancedArrival_le_modeBound
#print axioms KL2003.GeneralKAdvancedArrivalBoundedness.exists_uniform_advanced_gap
#print axioms KL2003.GeneralKAdvancedArrivalBoundedness.exists_boundedAdvancedPair
#print axioms KL2003.GeneralKAdvancedArrivalBoundedness.exists_uniform_boundedAdvancedPair_drop
#print axioms KL2003.GeneralKAdvancedArrivalBoundedness.nonnegative_branch_impossible_of_advancedArrivalsNonincreasing
#print axioms KL2003.GeneralKAdvancedArrivalBoundedness.criticalScheduler_not_neverStops
#print axioms KL2003.GeneralKAdvancedArrivalBoundedness.exists_criticalScheduler_stop
#print axioms KL2003.GeneralKAdvancedArrivalBoundedness.exists_criticalTerminalShiftsNegative
