import CollatzClassical.KL2003.KL2003GeneralKCriticalInfiniteBranchExtraction

open CollatzClassical KL2003

#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.nonempty_selectedCodeAtDepth
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.exists_coherent_selectedCodes
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.sourceWalkActionList_chainCoherent
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.coherentSelectedCodes_succ
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.coherentPackedStream_take
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.coherentPackedStream_adjacent
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.extractedInfiniteSourceWalk
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.extractedInfiniteSourceWalk_segment_code
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.extractedInfiniteSourceWalk_prefix_isSelected
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.run_allStrictPrefixesNonnegative
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.selectedCodePrefix_nonnegative
#print axioms KL2003.GeneralKCriticalInfiniteBranchExtraction.extractedInfiniteSourceWalk_shiftsNonnegative
