import CollatzClassical.KL2003.KL2003GeneralKInfiniteBranchExtraction

open CollatzClassical KL2003

#print axioms KL2003.GeneralKInfiniteBranchExtraction.nonempty_selectedCodeAtDepth
#print axioms KL2003.GeneralKInfiniteBranchExtraction.exists_coherent_selectedCodes
#print axioms KL2003.GeneralKInfiniteBranchExtraction.sourceWalkActionList_chainCoherent
#print axioms KL2003.GeneralKInfiniteBranchExtraction.coherentSelectedCodes_succ
#print axioms KL2003.GeneralKInfiniteBranchExtraction.coherentPackedStream_take
#print axioms KL2003.GeneralKInfiniteBranchExtraction.coherentPackedStream_adjacent
#print axioms KL2003.GeneralKInfiniteBranchExtraction.extractedInfiniteSourceWalk
#print axioms KL2003.GeneralKInfiniteBranchExtraction.extractedInfiniteSourceWalk_segment_code
#print axioms KL2003.GeneralKInfiniteBranchExtraction.extractedInfiniteSourceWalk_prefix_isSelected
