import CollatzClassical.KL2003.KL2003GeneralKAdvancedPrefixRealization

open CollatzClassical KL2003

#print axioms KL2003.GeneralKAdvancedPrefixRealization.advancePackedShift_eval
#print axioms KL2003.GeneralKAdvancedPrefixRealization.packedPrefixLabels_get_mode
#print axioms KL2003.GeneralKAdvancedPrefixRealization.packedPrefixLabels_get_shift
#print axioms KL2003.GeneralKAdvancedPrefixRealization.advancePackedShift_extractedPrefix_eval
#print axioms KL2003.GeneralKAdvancedPrefixRealization.target_shift_eval_eq_beta
#print axioms KL2003.GeneralKAdvancedPrefixRealization.earlier_prefix_label
#print axioms KL2003.GeneralKAdvancedPrefixRealization.advancedArrivalsNonincreasing_of_allAdvancedPrefixesWitnessFree
#print axioms KL2003.GeneralKAdvancedPrefixRealization.extracted_exists_strictly_decreasing_recurrent_advanced_arrivals
