import CollatzClassical.DensityFusionNamedContract

#print axioms CollatzClassical.NamedDensityFusionContract.eventual_lower_bound
#print axioms
  CollatzClassical.NamedDensityFusionContract.positive_eventual_ratio_lower_bound
